# **Dicoding Indonesia: Belajar Fundamental Deep Learning**
# Proyek NLP Analisis Sentiment 
**Analisis sentimen review aplikasi game Mobile Legends pada Play Store dengan Pendekatan Random Forrest dan Super Vector Machince (SVM).**

# 0.Import Library

In [ ]:
import re  
import csv
import nltk 
import requests
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

from io import StringIO
from gensim.models import Word2Vec
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize  
from sklearn.metrics import accuracy_score
from Sastrawi.Stemmer.StemmerFactory import (StemmerFactory) 
from sklearn.feature_extraction.text import TfidfVectorizer

# python -m pip install sastrawi
nltk.download("punkt_tab")  
nltk.download("stopwords")

[nltk_data] Downloading package punkt_tab to C:\Users\Febryo Fibonacci
[nltk_data]     A\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Febryo Fibonacci
[nltk_data]     A\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

# 2.Loading Dataset

In [ ]:
df = pd.DataFrame("Ulasan_APK_Mobile_Legends.csv")
df.head(-10)

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,a5f8f395-4d19-413c-84a3-6c5bb9065d21,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"hallo admin yth, tolong perbaiki masalah solo ...",3,2,2.1.95.12053,2026-08-16 15:54:09,NaN,NaT,2.1.95.12053
1,02c9b2d8-fa0e-4644-b506-10fddd7aed4a,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Sebenarnya udah bagus banget, dari Matchmaking...",5,7,2.1.95.12053,2026-08-13 19:05:53,NaN,NaT,2.1.95.12053
2,c66b5494-4ed1-45af-85b3-6dc752e590d1,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Kpd moonton terhormat. Banyak sekali komplen s...,1,3,2.1.95.12053,2026-08-20 16:59:53,NaN,NaT,2.1.95.12053
3,76c2e484-e9a3-40ad-b353-079132d5b031,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"bukan maksud untuk menjelekan, tapi sering sek...",3,3,2.1.95.12053,2026-08-20 20:58:02,NaN,NaT,2.1.95.12053
4,75ff1320-d876-499c-9543-fe80999f9783,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"game jelek, gak recomended, sinyal Wifi diruma...",1,3,2.1.95.12053,2026-08-17 14:40:15,"Halo Kak,\nMaaf atas masalah jaringan yang Kak...",2026-08-17 16:17:22,2.1.95.12053
...,...,...,...,...,...,...,...,...,...,...,...
341985,9e837ce3-840e-4aa4-bf31-7fb8e15e6353,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Semakin lama semakin kocak ini apk, jaringan 4...",1,0,1.5.38.5881,2023-06-10 14:35:28,NaN,NaT,1.5.38.5881
341986,d964ecac-6bbb-4ee6-b719-87da27573a9d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Game tidak bermutu Lebih banyak kalah dan tim ...,1,0,1.9.43.10342,2025-01-12 03:04:40,NaN,NaT,1.9.43.10342
341987,af32fbac-46f2-488e-91ec-049731965d15,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Makin kesini makin naik aja udah gak kuat hap ...,1,0,NaN,2023-09-01 04:29:48,NaN,NaT,NaN
341988,36aac986-c81f-487d-a2f7-babd0b7a7309,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Bukan gamenya yg rusak tetapi HP kalian semua ...,5,0,1.7.26.7851,2022-10-29 20:39:35,NaN,NaT,1.7.26.7851
341989,04928e93-76f1-435f-a480-d6f2883a9a4e,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Gausah update² trus lah moontod device gua nge...,2,0,NaN,2024-03-13 22:05:20,NaN,NaT,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 342000 entries, 0 to 341999
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   reviewId              342000 non-null  str
 1   userName              342000 non-null  str
 2   userImage             342000 non-null  str
 3   content               342000 non-null  str
 4   score                 342000 non-null  int64
 5   thumbsUpCount         342000 non-null  int64
 6   reviewCreatedVersion  254480 non-null  str
 7   at                    342000 non-null  datetime64[us]
 8   replyContent          21838 non-null   str
 9   repliedAt             21838 non-null   datetime64[us]
 10  appVersion            254480 non-null  str
dtypes: datetime64[us](2), int64(2), str(7)
memory usage: 28.7 MB

In [5]:
df.shape

(342000, 11)

In [6]:
def get_missing_values(data):
    missing = pd.DataFrame({
        "Missing Values": data.isna().sum(),
        "Perncentage": (data.isna().sum() / len(data) * 100).round(2) 
    })

    return missing

def get_duplicated_row(data):
    print("Duplicated Rows:", data.duplicated)

In [7]:
get_missing_values(df)

                      Missing Values  Perncentage
reviewId                           0         0.00
userName                           0         0.00
userImage                          0         0.00
content                            0         0.00
score                              0         0.00
thumbsUpCount                      0         0.00
reviewCreatedVersion           87520        25.59
at                                 0         0.00
replyContent                  320162        93.61
repliedAt                     320162        93.61
appVersion                     87520        25.59

In [8]:
get_duplicated_row(df)

Duplicated Rows: <bound method DataFrame.duplicated of                                     reviewId         userName  \
0       a5f8f395-4d19-413c-84a3-6c5bb9065d21  Pengguna Google
1       02c9b2d8-fa0e-4644-b506-10fddd7aed4a  Pengguna Google
2       c66b5494-4ed1-45af-85b3-6dc752e590d1  Pengguna Google
3       76c2e484-e9a3-40ad-b353-079132d5b031  Pengguna Google
4       75ff1320-d876-499c-9543-fe80999f9783  Pengguna Google
...                                      ...              ...
341995  68cd8887-1c5c-462d-980d-f454cb1d2223  Pengguna Google
341996  2a75ea48-8ecc-4688-a437-8c6c2f3d05d4  Pengguna Google
341997  a607b92d-25ca-4c25-837b-2a44c7fb49bd  Pengguna Google
341998  d0135776-4255-45c6-b9a6-8b4bee97337f  Pengguna Google
341999  0938e59a-5e54-409f-b4f9-772f6a6b8ee0  Pengguna Google

                                                userImage  \
0       https://play-lh.googleusercontent.com/EGemoI2N...
1       https://play-lh.googleusercontent.com/EGemoI2N...
2       https://play-lh.googleusercontent.com/EGemoI2N...
3       https://play-lh.googleusercontent.com/EGemoI2N...
4       https://play-lh.googleusercontent.com/EGemoI2N...
...                                                   ...
341995  https://play-lh.googleusercontent.com/EGemoI2N...
341996  https://play-lh.googleusercontent.com/EGemoI2N...
341997  https://play-lh.googleusercontent.com/EGemoI2N...
341998  https://play-lh.googleusercontent.com/EGemoI2N...
341999  https://play-lh.googleusercontent.com/EGemoI2N...

                                                  content  score  \
0       hallo admin yth, tolong perbaiki masalah solo ...      3
1       Sebenarnya udah bagus banget, dari Matchmaking...      5
2       Kpd moonton terhormat. Banyak sekali komplen s...      1
3       bukan maksud untuk menjelekan, tapi sering sek...      3
4       game jelek, gak recomended, sinyal Wifi diruma...      1
...                                                   ...    ...
341995  Nice game!Cman terkadang ketemu player keras k...      5
341996  game nya sih bagus tapi kalo kaitkan akun ataw...      3
341997  sinyal tiba tiba menghilang dan tidak bisa kem...      1
341998  Em permainan ya seru gitu, soalnya pemain ya l...      5
341999                 Kurangilah data untuk hp ram kecil      3

        thumbsUpCount reviewCreatedVersion                  at  \
0                   2         2.1.95.12053 2026-08-16 15:54:09
1                   7         2.1.95.12053 2026-08-13 19:05:53
2                   3         2.1.95.12053 2026-08-20 16:59:53
3                   3         2.1.95.12053 2026-08-20 20:58:02
4                   3         2.1.95.12053 2026-08-17 14:40:15
...               ...                  ...                 ...
341995              0                  NaN 2019-12-01 19:35:03
341996              0                  NaN 2019-01-13 20:03:08
341997              0               1.4.09 2019-09-01 00:51:27
341998              0          1.6.35.6931 2021-12-27 13:37:38
341999              0                  NaN 2023-09-23 22:38:55

                                             replyContent           repliedAt  \
0                                                     NaN                 NaT
1                                                     NaN                 NaT
2                                                     NaN                 NaT
3                                                     NaN                 NaT
4       Halo Kak,\nMaaf atas masalah jaringan yang Kak... 2026-08-17 16:17:22
...                                                   ...                 ...
341995                                                NaN                 NaT
341996                                                NaN                 NaT
341997                                                NaN                 NaT
341998                                                NaN                 NaT
341999                                                NaN                 NaT

          appVersion
0       2.1.95.12053
1       2.1.95.12053
2       2.1.95.12053
3       2.1.95.12053
4       2.1.95.12053
...              ...
341995           NaN
341996           NaN
341997        1.4.09
341998   1.6.35.6931
341999           NaN

[342000 rows x 11 columns]>

In [9]:
# Clean missing values dan duplicated rows
df_clean = df.dropna()
df_clean = df_clean.drop_duplicates()

In [10]:
get_missing_values(df_clean)

                      Missing Values  Perncentage
reviewId                           0          0.0
userName                           0          0.0
userImage                          0          0.0
content                            0          0.0
score                              0          0.0
thumbsUpCount                      0          0.0
reviewCreatedVersion               0          0.0
at                                 0          0.0
replyContent                       0          0.0
repliedAt                          0          0.0
appVersion                         0          0.0

In [11]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 17589 entries, 4 to 341856
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              17589 non-null  str
 1   userName              17589 non-null  str
 2   userImage             17589 non-null  str
 3   content               17589 non-null  str
 4   score                 17589 non-null  int64
 5   thumbsUpCount         17589 non-null  int64
 6   reviewCreatedVersion  17589 non-null  str
 7   at                    17589 non-null  datetime64[us]
 8   replyContent          17589 non-null  str
 9   repliedAt             17589 non-null  datetime64[us]
 10  appVersion            17589 non-null  str
dtypes: datetime64[us](2), int64(2), str(7)
memory usage: 1.6 MB

# 3.Text Preprocessing

In [12]:
# Case folding text
df_clean["text_lowercase"] = df["content"].str.lower()
df_clean["text_lowercase"]

4         game jelek, gak recomended, sinyal wifi diruma...
15        sistem apaan ini?? setim dengan player rank le...
16        saya mengajukan keberatan atas dugaan pengguna...
17        tolong fitur highlight nya dibikin otomatis te...
33        tolong banget ya, kenapa ini banyak komputer a...
                                ...
341536    untuk jaringan tolong d perbaiki masa sinyal t...
341778    mats tidak seimbang lawan main nya di atas rat...
341836    pembagian tim ngawur, tim sendiri gabisa maen,...
341854    moonton tolong la perbaiki sistem pertandingan...
341856    akun dulu tidak bisa kembali, padahal sudah sa...
Name: text_lowercase, Length: 17589, dtype: str

In [13]:
df_clean["text_clean"] = df_clean.apply(lambda x: re.sub(r"^[^-]*-\s", "", x["text_lowercase"]), axis=1)
df_clean["text_clean"]

4         game jelek, gak recomended, sinyal wifi diruma...
15        sistem apaan ini?? setim dengan player rank le...
16        saya mengajukan keberatan atas dugaan pengguna...
17        tolong fitur highlight nya dibikin otomatis te...
33        tolong banget ya, kenapa ini banyak komputer a...
                                ...
341536    untuk jaringan tolong d perbaiki masa sinyal t...
341778    mats tidak seimbang lawan main nya di atas rat...
341836    pembagian tim ngawur, tim sendiri gabisa maen,...
341854    moonton tolong la perbaiki sistem pertandingan...
341856    akun dulu tidak bisa kembali, padahal sudah sa...
Name: text_clean, Length: 17589, dtype: str

In [14]:
# Delete mention
df_clean["text_clean"] = df_clean.apply(lambda x: re.sub(r"@[A-Za-z0-9]+", "", x["text_clean"]), axis=1)

# Delete hashtag
df_clean["text_clean"] = df_clean.apply(lambda x: re.sub(r"#[A-Za-z0-9]+", "", x["text_clean"]), axis=1)

# Delete RT
df_clean["text_clean"] = df_clean.apply(lambda x: re.sub(r"RT[\s]", "", x["text_clean"]), axis=1)

# Delete link
df_clean["text_clean"] = df_clean.apply(lambda x: re.sub(r"http\S+", "", x["text_clean"]), axis=1)

# Delete angka
df_clean["text_clean"] = df_clean.apply(lambda x: re.sub(r"[0-9]+", "", x["text_clean"]), axis=1)

# Delete punctuation
df_clean["text_clean"] = df_clean.apply(lambda x: re.sub(r"[^\w\s]", "", x["text_clean"]), axis=1)


df_clean["text_clean"]

4         game jelek gak recomended sinyal wifi dirumah ...
15        sistem apaan ini setim dengan player rank lebi...
16        saya mengajukan keberatan atas dugaan pengguna...
17        tolong fitur highlight nya dibikin otomatis te...
33        tolong banget ya kenapa ini banyak komputer ai...
                                ...
341536    untuk jaringan tolong d perbaiki masa sinyal t...
341778    mats tidak seimbang lawan main nya di atas rat...
341836    pembagian tim ngawur tim sendiri gabisa maenda...
341854    moonton tolong la perbaiki sistem pertandingan...
341856    akun dulu tidak bisa kembali padahal sudah say...
Name: text_clean, Length: 17589, dtype: str

In [15]:
# slangwords
# Mengganti kata-kata slang dengan kata-kata standar dan menyimpannya di 'text_slangwords'
slangwords = {
    "@": "di",
    "abis": "habis",
    "wtb": "beli",
    "masi": "masih",
    "wts": "jual",
    "wtt": "tukar",
    "bgt": "banget",
    "maks": "maksimal",
}

df_clean["text_clean"] = df_clean.apply(lambda x: " ".join([slangwords.get(word.lower(), word) for word in x["text_clean"].split()]),axis=1)
df_clean["text_clean"]

4         game jelek gak recomended sinyal wifi dirumah ...
15        sistem apaan ini setim dengan player rank lebi...
16        saya mengajukan keberatan atas dugaan pengguna...
17        tolong fitur highlight nya dibikin otomatis te...
33        tolong banget ya kenapa ini banyak komputer ai...
                                ...
341536    untuk jaringan tolong d perbaiki masa sinyal t...
341778    mats tidak seimbang lawan main nya di atas rat...
341836    pembagian tim ngawur tim sendiri gabisa maenda...
341854    moonton tolong la perbaiki sistem pertandingan...
341856    akun dulu tidak bisa kembali padahal sudah say...
Name: text_clean, Length: 17589, dtype: str

In [16]:
# Remove stopwords
stopwords_id = stopwords.words("indonesian")
stopword_tambahan = [
            "iya",
            "yaa",
            "gak",
            "nya",
            "na",
            "sih",
            "ku",
            "di",
            "ga",
            "ya",
            "gaa",
            "loh",
            "kah",
            "woi",
            "woii",
            "woy",
        ]
stopwords_id.extend(stopword_tambahan)
stopwords_id

['ada',
 'adalah',
 'adanya',
 'adapun',
 'agak',
 'agaknya',
 'agar',
 'akan',
 'akankah',
 'akhir',
 'akhiri',
 'akhirnya',
 'aku',
 'akulah',
 'amat',
 'amatlah',
 'anda',
 'andalah',
 'antar',
 'antara',
 'antaranya',
 'apa',
 'apaan',
 'apabila',
 'apakah',
 'apalagi',
 'apatah',
 'artinya',
 'asal',
 'asalkan',
 'atas',
 'atau',
 'ataukah',
 'ataupun',
 'awal',
 'awalnya',
 'bagai',
 'bagaikan',
 'bagaimana',
 'bagaimanakah',
 'bagaimanapun',
 'bagi',
 'bagian',
 'bahkan',
 'bahwa',
 'bahwasanya',
 'baik',
 'bakal',
 'bakalan',
 'balik',
 'banyak',
 'bapak',
 'baru',
 'bawah',
 'beberapa',
 'begini',
 'beginian',
 'beginikah',
 'beginilah',
 'begitu',
 'begitukah',
 'begitulah',
 'begitupun',
 'bekerja',
 'belakang',
 'belakangan',
 'belum',
 'belumlah',
 'benar',
 'benarkah',
 'benarlah',
 'berada',
 'berakhir',
 'berakhirlah',
 'berakhirnya',
 'berapa',
 'berapakah',
 'berapalah',
 'berapapun',
 'berarti',
 'berawal',
 'berbagai',
 'berdatangan',
 'beri',
 'berikan',
 'berikut',
 'berikutnya',
 'berjumlah',
 'berkali-kali',
 'berkata',
 'berkehendak',
 'berkeinginan',
 'berkenaan',
 'berlainan',
 'berlalu',
 'berlangsung',
 'berlebihan',
 'bermacam',
 'bermacam-macam',
 'bermaksud',
 'bermula',
 'bersama',
 'bersama-sama',
 'bersiap',
 'bersiap-siap',
 'bertanya',
 'bertanya-tanya',
 'berturut',
 'berturut-turut',
 'bertutur',
 'berujar',
 'berupa',
 'besar',
 'betul',
 'betulkah',
 'biasa',
 'biasanya',
 'bila',
 'bilakah',
 'bisa',
 'bisakah',
 'boleh',
 'bolehkah',
 'bolehlah',
 'buat',
 'bukan',
 'bukankah',
 'bukanlah',
 'bukannya',
 'bulan',
 'bung',
 'cara',
 'caranya',
 'cukup',
 'cukupkah',
 'cukuplah',
 'cuma',
 'dahulu',
 'dalam',
 'dan',
 'dapat',
 'dari',
 'daripada',
 'datang',
 'dekat',
 'demi',
 'demikian',
 'demikianlah',
 'dengan',
 'depan',
 'di',
 'dia',
 'diakhiri',
 'diakhirinya',
 'dialah',
 'diantara',
 'diantaranya',
 'diberi',
 'diberikan',
 'diberikannya',
 'dibuat',
 'dibuatnya',
 'didapat',
 'didatangkan',
 'digunakan',
 'diibaratkan',
 'diibaratkannya',
 'diingat',
 'diingatkan',
 'diinginkan',
 'dijawab',
 'dijelaskan',
 'dijelaskannya',
 'dikarenakan',
 'dikatakan',
 'dikatakannya',
 'dikerjakan',
 'diketahui',
 'diketahuinya',
 'dikira',
 'dilakukan',
 'dilalui',
 'dilihat',
 'dimaksud',
 'dimaksudkan',
 'dimaksudkannya',
 'dimaksudnya',
 'diminta',
 'dimintai',
 'dimisalkan',
 'dimulai',
 'dimulailah',
 'dimulainya',
 'dimungkinkan',
 'dini',
 'dipastikan',
 'diperbuat',
 'diperbuatnya',
 'dipergunakan',
 'diperkirakan',
 'diperlihatkan',
 'diperlukan',
 'diperlukannya',
 'dipersoalkan',
 'dipertanyakan',
 'dipunyai',
 'diri',
 'dirinya',
 'disampaikan',
 'disebut',
 'disebutkan',
 'disebutkannya',
 'disini',
 'disinilah',
 'ditambahkan',
 'ditandaskan',
 'ditanya',
 'ditanyai',
 'ditanyakan',
 'ditegaskan',
 'ditujukan',
 'ditunjuk',
 'ditunjuki',
 'ditunjukkan',
 'ditunjukkannya',
 'ditunjuknya',
 'dituturkan',
 'dituturkannya',
 'diucapkan',
 'diucapkannya',
 'diungkapkan',
 'dong',
 'dua',
 'dulu',
 'empat',
 'enggak',
 'enggaknya',
 'entah',
 'entahlah',
 'guna',
 'gunakan',
 'hal',
 'hampir',
 'hanya',
 'hanyalah',
 'hari',
 'harus',
 'haruslah',
 'harusnya',
 'hendak',
 'hendaklah',
 'hendaknya',
 'hingga',
 'ia',
 'ialah',
 'ibarat',
 'ibaratkan',
 'ibaratnya',
 'ibu',
 'ikut',
 'ingat',
 'ingat-ingat',
 'ingin',
 'inginkah',
 'inginkan',
 'ini',
 'inikah',
 'inilah',
 'itu',
 'itukah',
 'itulah',
 'jadi',
 'jadilah',
 'jadinya',
 'jangan',
 'jangankan',
 'janganlah',
 'jauh',
 'jawab',
 'jawaban',
 'jawabnya',
 'jelas',
 'jelaskan',
 'jelaslah',
 'jelasnya',
 'jika',
 'jikalau',
 'juga',
 'jumlah',
 'jumlahnya',
 'justru',
 'kala',
 'kalau',
 'kalaulah',
 'kalaupun',
 'kalian',
 'kami',
 'kamilah',
 'kamu',
 'kamulah',
 'kan',
 'kapan',
 'kapankah',
 'kapanpun',
 'karena',
 'karenanya',
 'kasus',
 'kata',
 'katakan',
 'katakanlah',
 'katanya',
 'ke',
 'keadaan',
 'kebetulan',
 'kecil',
 'kedua',
 'keduanya',
 'keinginan',
 'kelamaan',
 'kelihatan',
 'kelihatannya',
 'kelima',
 'keluar',
 'kembali',
 'kemudian',
 'kemungkinan',
 'kemungkinannya',
 'kenapa',
 'kepada',
 'kepadanya',
 'kesampaian',
 'keseluruhan',
 'keseluruhannya',
 'keterlaluan',
 'ketika',
 'khususnya',
 'kini',
 'kinilah',
 'kira',
 'kira-kira',
 'kiranya',
 'kita',
 'kitalah',
 'kok',
 'kurang',
 'lagi',
 'lagian',
 'lah',
 'lain',
 'lainnya',
 'lalu',
 'lama',
 'lamanya',
 'lanjut',
 'lanjutnya',
 'lebih',
 'lewat',
 'lima',
 'luar',
 'macam',
 'maka',
 'makanya',
 'makin',
 'malah',
 'malahan',
 'mampu',
 'mampukah',
 'mana',
 'manakala',
 'manalagi',
 'masa',
 'masalah',
 'masalahnya',
 'masih',
 'masihkah',
 'masing',
 'masing-masing',
 'mau',
 'maupun',
 'melainkan',
 'melakukan',
 'melalui',
 'melihat',
 'melihatnya',
 'memang',
 'memastikan',
 'memberi',
 'memberikan',
 'membuat',
 'memerlukan',
 'memihak',
 'meminta',
 'memintakan',
 'memisalkan',
 'memperbuat',
 'mempergunakan',
 'memperkirakan',
 'memperlihatkan',
 'mempersiapkan',
 'mempersoalkan',
 'mempertanyakan',
 'mempunyai',
 'memulai',
 'memungkinkan',
 'menaiki',
 'menambahkan',
 'menandaskan',
 'menanti',
 'menanti-nanti',
 'menantikan',
 'menanya',
 'menanyai',
 'menanyakan',
 'mendapat',
 'mendapatkan',
 'mendatang',
 'mendatangi',
 'mendatangkan',
 'menegaskan',
 'mengakhiri',
 'mengapa',
 'mengatakan',
 'mengatakannya',
 'mengenai',
 'mengerjakan',
 'mengetahui',
 'menggunakan',
 'menghendaki',
 'mengibaratkan',
 'mengibaratkannya',
 'mengingat',
 'mengingatkan',
 'menginginkan',
 'mengira',
 'mengucapkan',
 'mengucapkannya',
 'mengungkapkan',
 'menjadi',
 'menjawab',
 'menjelaskan',
 'menuju',
 'menunjuk',
 'menunjuki',
 'menunjukkan',
 'menunjuknya',
 'menurut',
 'menuturkan',
 'menyampaikan',
 'menyangkut',
 'menyatakan',
 'menyebutkan',
 'menyeluruh',
 'menyiapkan',
 'merasa',
 'mereka',
 'merekalah',
 'merupakan',
 'meski',
 'meskipun',
 'meyakini',
 'meyakinkan',
 'minta',
 'mirip',
 'misal',
 'misalkan',
 'misalnya',
 'mula',
 'mulai',
 'mulailah',
 'mulanya',
 'mungkin',
 'mungkinkah',
 'nah',
 'naik',
 'namun',
 'nanti',
 'nantinya',
 'nyaris',
 'nyatanya',
 'oleh',
 'olehnya',
 'pada',
 'padahal',
 'padanya',
 'pak',
 'paling',
 'panjang',
 'pantas',
 'para',
 'pasti',
 'pastilah',
 'penting',
 'pentingnya',
 'per',
 'percuma',
 'perlu',
 'perlukah',
 'perlunya',
 'pernah',
 'persoalan',
 'pertama',
 'pertama-tama',
 'pertanyaan',
 'pertanyakan',
 'pihak',
 'pihaknya',
 'pukul',
 'pula',
 'pun',
 'punya',
 'rasa',
 'rasanya',
 'rata',
 'rupanya',
 'saat',
 'saatnya',
 'saja',
 'sajalah',
 'saling',
 'sama',
 'sama-sama',
 'sambil',
 'sampai',
 'sampai-sampai',
 'sampaikan',
 'sana',
 'sangat',
 'sangatlah',
 'satu',
 'saya',
 'sayalah',
 'se',
 'sebab',
 'sebabnya',
 'sebagai',
 'sebagaimana',
 'sebagainya',
 'sebagian',
 'sebaik',
 'sebaik-baiknya',
 'sebaiknya',
 'sebaliknya',
 'sebanyak',
 'sebegini',
 'sebegitu',
 'sebelum',
 'sebelumnya',
 'sebenarnya',
 'seberapa',
 'sebesar',
 'sebetulnya',
 'sebisanya',
 'sebuah',
 'sebut',
 'sebutlah',
 'sebutnya',
 'secara',
 'secukupnya',
 'sedang',
 'sedangkan',
 'sedemikian',
 'sedikit',
 'sedikitnya',
 'seenaknya',
 'segala',
 'segalanya',
 'segera',
 'seharusnya',
 'sehingga',
 'seingat',
 'sejak',
 'sejauh',
 'sejenak',
 'sejumlah',
 'sekadar',
 'sekadarnya',
 'sekali',
 'sekali-kali',
 'sekalian',
 'sekaligus',
 'sekalipun',
 'sekarang',
 'sekarang',
 'sekecil',
 'seketika',
 'sekiranya',
 'sekitar',
 'sekitarnya',
 'sekurang-kurangnya',
 'sekurangnya',
 'sela',
 'selain',
 'selaku',
 'selalu',
 'selama',
 'selama-lamanya',
 'selamanya',
 'selanjutnya',
 'seluruh',
 'seluruhnya',
 'semacam',
 'semakin',
 'semampu',
 'semampunya',
 'semasa',
 'semasih',
 'semata',
 'semata-mata',
 'semaunya',
 'sementara',
 'semisal',
 'semisalnya',
 'sempat',
 'semua',
 'semuanya',
 'semula',
 'sendiri',
 'sendirian',
 'sendirinya',
 'seolah',
 'seolah-olah',
 'seorang',
 'sepanjang',
 'sepantasnya',
 'sepantasnyalah',
 'seperlunya',
 'seperti',
 'sepertinya',
 'sepihak',
 'sering',
 'seringnya',
 'serta',
 'serupa',
 'sesaat',
 'sesama',
 'sesampai',
 'sesegera',
 'sesekali',
 'seseorang',
 'sesuatu',
 'sesuatunya',
 'sesudah',
 'sesudahnya',
 'setelah',
 'setempat',
 'setengah',
 'seterusnya',
 'setiap',
 'setiba',
 'setibanya',
 'setidak-tidaknya',
 'setidaknya',
 'setinggi',
 'seusai',
 'sewaktu',
 'siap',
 'siapa',
 'siapakah',
 'siapapun',
 'sini',
 'sinilah',
 'soal',
 'soalnya',
 'suatu',
 'sudah',
 'sudahkah',
 'sudahlah',
 'supaya',
 'tadi',
 'tadinya',
 'tahu',
 'tahun',
 'tak',
 'tambah',
 'tambahnya',
 'tampak',
 'tampaknya',
 'tandas',
 'tandasnya',
 'tanpa',
 'tanya',
 'tanyakan',
 'tanyanya',
 'tapi',
 'tegas',
 'tegasnya',
 'telah',
 'tempat',
 'tengah',
 'tentang',
 'tentu',
 'tentulah',
 'tentunya',
 'tepat',
 'terakhir',
 'terasa',
 'terbanyak',
 'terdahulu',
 'terdapat',
 'terdiri',
 'terhadap',
 'terhadapnya',
 'teringat',
 'teringat-ingat',
 'terjadi',
 'terjadilah',
 'terjadinya',
 'terkira',
 'terlalu',
 'terlebih',
 'terlihat',
 'termasuk',
 'ternyata',
 'tersampaikan',
 'tersebut',
 'tersebutlah',
 'tertentu',
 'tertuju',
 'terus',
 'terutama',
 'tetap',
 'tetapi',
 'tiap',
 'tiba',
 'tiba-tiba',
 'tidak',
 'tidakkah',
 'tidaklah',
 'tiga',
 'tinggi',
 'toh',
 'tunjuk',
 'turut',
 'tutur',
 'tuturnya',
 'ucap',
 'ucapnya',
 'ujar',
 'ujarnya',
 'umum',
 'umumnya',
 'ungkap',
 'ungkapnya',
 'untuk',
 'usah',
 'usai',
 'waduh',
 'wah',
 'wahai',
 'waktu',
 'waktunya',
 'walau',
 'walaupun',
 'wong',
 'yaitu',
 'yakin',
 'yakni',
 'yang',
 'iya',
 'yaa',
 'gak',
 'nya',
 'na',
 'sih',
 'ku',
 'di',
 'ga',
 'ya',
 'gaa',
 'loh',
 'kah',
 'woi',
 'woii',
 'woy']

In [17]:
df_clean["text_clean"] = df_clean.apply(lambda x: " ".join([word for word in x["text_clean"].split() if word not in (stopwords_id)]), axis=1)
df_clean["text_clean"]

4         game jelek recomended sinyal wifi dirumah bagu...
15        sistem setim player rank gw main cover tim fig...
16        mengajukan keberatan dugaan penggunaan ai trai...
17        tolong fitur highlight dibikin otomatis tersim...
33        tolong banget komputer ai rank honor main solo...
                                ...
341536    jaringan tolong d perbaiki sinyal tibal merah ...
341778    mats seimbang lawan main rataa tim tolong perb...
341836    pembagian tim ngawur tim gabisa maendapet lawa...
341854    moonton tolong la perbaiki sistem pertandingan...
341856                        akun kaitkan akun google play
Name: text_clean, Length: 17589, dtype: str

In [18]:
# Tokenize
df_clean["token"] = df_clean.apply(lambda x: word_tokenize(x["text_clean"]), axis=1)
df_clean["token"]

4         [game, jelek, recomended, sinyal, wifi, diruma...
15        [sistem, setim, player, rank, gw, main, cover,...
16        [mengajukan, keberatan, dugaan, penggunaan, ai...
17        [tolong, fitur, highlight, dibikin, otomatis, ...
33        [tolong, banget, komputer, ai, rank, honor, ma...
                                ...
341536    [jaringan, tolong, d, perbaiki, sinyal, tibal,...
341778    [mats, seimbang, lawan, main, rataa, tim, tolo...
341836    [pembagian, tim, ngawur, tim, gabisa, maendape...
341854    [moonton, tolong, la, perbaiki, sistem, pertan...
341856                  [akun, kaitkan, akun, google, play]
Name: token, Length: 17589, dtype: object

In [19]:
# Stemming
factory = StemmerFactory()
stemmer = factory.create_stemmer()

df_clean["stemmed"] = df_clean["token"].apply(lambda tokens: [stemmer.stem(token) for token in tokens])
df_clean["stemmed"]

4         [game, jelek, recomended, sinyal, wifi, rumah,...
15        [sistem, tim, player, rank, gw, main, cover, t...
16        [aju, berat, duga, guna, ai, trainingbot, matc...
17        [tolong, fitur, highlight, bikin, otomatis, si...
33        [tolong, banget, komputer, ai, rank, honor, ma...
                                ...
341536    [jaring, tolong, d, baik, sinyal, tibal, merah...
341778    [mats, imbang, lawan, main, rataa, tim, tolong...
341836    [bagi, tim, ngawur, tim, gabisa, maendapet, la...
341854    [moonton, tolong, la, baik, sistem, tanding, k...
341856                     [akun, kait, akun, google, play]
Name: stemmed, Length: 17589, dtype: object

# 4.Labeling

In [20]:
# Membaca data kamus kata-kata positif dari GitHub
lexicon_positive = dict()

# Mengirim permintaan HTTP untuk mendapatkan file CSV dari GitHub
response = requests.get(
    "https://raw.githubusercontent.com/angelmetanosaa/dataset/main/lexicon_positive.csv"
)

response

In [21]:
if response.status_code == 200:

    # Membaca teks response dalam bentuk csv dengan pembaca CSV dan pemisah koma
    reader = csv.reader(StringIO(response.text), delimiter=",")

    lexicon_positive = {row[0]: int(row[1]) for row in reader}

else:
    print("Failed to fetch positive lexicon data")

lexicon_positive

{'hai': 3,
 'merekam': 2,
 'ekstensif': 3,
 'paripurna': 1,
 'detail': 2,
 'pernik': 3,
 'belas': 2,
 'welas': 4,
 'kabung': 1,
 'rahayu': 4,
 'maaf': 2,
 'hello': 2,
 'promo': 3,
 'terimakasih': 5,
 'cover': 3,
 'mohon': 2,
 'mengawal': 2,
 'statistik': 1,
 'keluangan': 3,
 'jalan terbuka': 3,
 'banyaknya': 3,
 'lebar': 3,
 'bentang': 1,
 'hendaknya': 1,
 'silahkan': 3,
 'semboyan': 2,
 'ditunggu': 2,
 'akses': 2,
 'penerangan': 2,
 'hi': 1,
 'dibantu': 2,
 'makasih': 4,
 'halo': 1,
 'thanks': 3,
 'pengembangan': 3,
 'diva': 2,
 'punya': 3,
 'tidak segan': 2,
 'detailnya': 1,
 'tak segan': 2,
 'aktivasi': 2,
 'asih': 3,
 'kasih sayang': 5,
 'kekaguman': 4,
 'kehangatan': 4,
 'afeksi': 2,
 'renjana': 2,
 'amor': 2,
 'cinta kasih': 5,
 'tresna': 2,
 'filantropi': 2,
 'cintrong': 2,
 'suasana (hati)': 1,
 'dinamika': 3,
 'tuhan': 3,
 'merespon': 3,
 'makmur': 4,
 'suka cita': 4,
 'pengguna': 1,
 'tunggu': 1,
 'lotre': 2,
 'nggak': 1,
 'kupon': 3,
 'terpelihara': 4,
 'terawat': 5,
 'tersadar': 3,
 'tari': 1,
 'gejolak': 1,
 'kejutan': 3,
 'pesta': 4,
 'getar': 1,
 'allah': 5,
 'berlabuh': 3,
 'terdaftar': 1,
 'negosiasi': 2,
 'revolusioner': 3,
 'follback': 1,
 'pelaminan': 4,
 'yasalamualaika': 3,
 'uang lelah': 2,
 'parsel': 2,
 'amplop': 3,
 'kenang-kenangan': 3,
 'pengasih': 4,
 'uang rokok': 2,
 'persenan': 2,
 'baksis': 2,
 'tanda mata': 2,
 'angpau': 4,
 'hibah': 4,
 'upa': 2,
 'bingkisan': 4,
 'suvenir': 4,
 'kesudian': 2,
 'berakar': 2,
 'para-para': 2,
 'termakan': 1,
 'kemasyhuran': 4,
 'reputasi': 2,
 'gelar': 2,
 'serep': 2,
 'invite': 1,
 'nyanyian': 2,
 'dendang': 2,
 'gita': 2,
 'gending': 1,
 'lagu': 2,
 'rintisan': 2,
 'bergelora': 2,
 'antusias': 2,
 'ringan tangan': 4,
 'membara': 2,
 'menyala': 2,
 'berlangganan': 2,
 'berdenyut': 2,
 'bersungguh-sungguh': 4,
 'rintis': 2,
 'jalan bebas hambatan': 2,
 'tarekat': 2,
 'bajing': 1,
 'bopong': 1,
 'berlezat': 2,
 'getaran': 1,
 'berperan serta': 2,
 'debar': 2,
 'raba': 1,
 'degub': 1,
 'ikut serta': 3,
 'berpartisipasi': 3,
 'menguntiti': 1,
 'penghayatan': 3,
 'mitra': 2,
 'diterima': 2,
 'sohib': 3,
 'beriktikad': 2,
 'berkeyakinan': 3,
 'beriman': 3,
 'percaya': 2,
 'menghajatkan': 1,
 'senyum': 2,
 'haloo': 3,
 'menarik hati': 3,
 'cedayam': 2,
 'hasan': 3,
 'tumandang': 1,
 'pengen': 3,
 'bener': 3,
 'hellooo': 2,
 'marilah': 1,
 'terbaik': 5,
 'ulung': 4,
 'good': 5,
 'silakan': 1,
 'main': 2,
 'alhamdulillah': 5,
 'unek-unek': 2,
 'sesalan': 1,
 'menyaksikan': 1,
 'pemenangnya': 4,
 'hiii': 1,
 'menyuarakan': 3,
 'menginterprestasikan': 1,
 'menaksir': 3,
 'menuturkan': 3,
 'memperkirakan': 2,
 'mengimla': 1,
 'mengantisipasi': 3,
 'menafsirkan': 2,
 'mengartikan': 1,
 'mengasosiasikan': 3,
 'borong': 2,
 'payu': 2,
 'membeli': 2,
 'membuat': 1,
 'tertawa kecil': 4,
 'minta': 2,
 'mengorak senyum': 2,
 'mesem': 2,
 'tersenyum': 4,
 'ok': 4,
 'ayo': 4,
 'mari': 4,
 'yuk': 4,
 'lincah': 4,
 'buru-buru': 1,
 'kencang': 3,
 'buntut': 1,
 'kilat': 3,
 'kunjung': 3,
 'mendahului': 2,
 'segera': 3,
 'lekas': 2,
 'akas': 2,
 'terampil': 4,
 'jeraus': 2,
 'pagi': 1,
 'pesat': 3,
 'sebat': 1,
 'kawal': 1,
 'berkawal': 4,
 'gugah': 2,
 'pustaka': 4,
 'sir-siran': 2,
 'pelihara': 3,
 'patroli': 2,
 'kitab': 2,
 'ronda': 2,
 'sambang': 2,
 'berguru': 3,
 'menuntut ilmu': 4,
 'melatih diri': 4,
 'menimba ilmu': 4,
 'mengaji': 4,
 'meneladan': 4,
 'mencari ilmu': 4,
 'luck': 4,
 'bersekolah': 3,
 'menggali ilmu': 4,
 'desak': 1,
 'menelaah': 2,
 'memahirkan': 4,
 'harmonisasiuniv': 2,
 'takut': 1,
 'sreg': 2,
 'penyatuan': 3,
 'wangi': 4,
 'pulas': 4,
 'merdu': 5,
 'harum': 5,
 'legit': 4,
 'inkorporasi': 3,
 'serundai': 2,
 'helloo': 1,
 'page': 2,
 'menyerempakkan': 3,
 'menyinkronkan': 1,
 'tolong': 3,
 'kediaman': 2,
 'panti': 2,
 'rumah': 3,
 'simplistis': 3,
 'menjejali': 1,
 'perfek': 4,
 'tayib': 2,
 'memejahijaukan': 1,
 'tayibah': 2,
 'jamil': 2,
 'mungil': 3,
 'rancak': 5,
 'mengisi': 2,
 'necis': 4,
 'menyidangkan': 1,
 'bagusan': 2,
 'estetis': 4,
 'firasat': 1,
 'cawis': 2,
 'berdandan': 4,
 'andini': 2,
 'indikasi': 2,
 'tersedia': 4,
 'tersaji': 4,
 'sholat': 5,
 'pastikan': 3,
 'tersuguh': 2,
 'perpanjangan': 2,
 'fiesta': 3,
 'terdamping': 1,
 'jomblo': 1,
 'medali': 4,
 'terdekat': 1,
 'artistik': 4,
 'wah': 3,
 'imut-imut': 4,
 'langkah baik': 4,
 'langkah kanan': 3,
 'guys': 1,
 'profit': 4,
 'waris': 3,
 'dominan': 3,
 'kooperasi': 1,
 'keras tulang': 2,
 'gedembal': 2,
 'tangguh': 5,
 'wedel': 2,
 'tapa': 2,
 'kedot': 2,
 'keikutsertaan': 3,
 'kesertaan': 2,
 'dibalas': 2,
 'kerja sama': 4,
 'tatap': 1,
 'berpengaruh': 3,
 'besar lengan': 3,
 'partisipasi': 3,
 'bedegap': 3,
 'peran serta': 3,
 'masif': 2,
 'gratis': 4,
 'membantu': 4,
 'busana': 2,
 'hasad': 2,
 'keki': 1,
 'free': 3,
 'wkwkwk': 3,
 'sangsi': 1,
 'berprasangka': 1,
 'bermaslahat': 2,
 'mujur': 4,
 'warisan': 3,
 'bersetuju': 3,
 'kenan': 2,
 '(hujan) gerimis': 1,
 'support': 4,
 'sahabat': 4,
 'gerimis': 1,
 'hujan': 1,
 'handai': 3,
 'kece': 5,
 'thank': 4,
 'hujan ringan': 2,
 'sobat': 4,
 'panjang tungkai': 2,
 'trims': 4,
 'doa': 4,
 'pacaran': 3,
 'berpacaran': 3,
 'teranyar': 4,
 'hallo': 4,
 'happy': 5,
 'ketemu': 1,
 'senjang': 1,
 'mudah-mudahan': 1,
 'modern': 3,
 'peranakan': 2,
 'pemudaan': 2,
 'masygul': 3,
 'gelebah': 2,
 'mending': 2,
 'regenerasi': 4,
 'simpel': 3,
 'sirap hati': 1,
 'puspa': 4,
 'mengenyam': 1,
 'merah telinga': 1,
 'bonafide': 3,
 'terbakar': 1,
 'bergairah': 3,
 'puspita': 3,
 'pelengkap': 2,
 'perempuan cantik': 5,
 'sewot': 1,
 'gusar': 1,
 'hiasan': 3,
 'kesuma': 3,
 'primadona': 5,
 'tulus ikhlas': 5,
 'senyuman': 4,
 'lugas': 4,
 'gemas': 4,
 'kusuma': 4,
 'yaudah': 1,
 'menyayang': 4,
 'menggemari': 3,
 'pasangan hidup': 4,
 'asah asih asuh': 2,
 'belom': 1,
 'hay': 1,
 'kepedulian': 4,
 'sepuh': 1,
 'kejelasan': 1,
 'seruh': 2,
 'terlukis': 3,
 'prosa': 2,
 'ketertarikan': 4,
 'cerita anak': 2,
 'bau tanah': 1,
 'atensi': 2,
 'tergambar': 2,
 'anekdot': 2,
 'mengamuk': 1,
 'shalat': 4,
 'lanjut': 2,
 'seneng': 5,
 'omong kosong': 1,
 'bombastis': 2,
 'fiksi': 2,
 'dzuhur': 1,
 'tips': 4,
 'kelonggaran': 3,
 'tq': 4,
 'respon': 2,
 'sirna': 1,
 'kelawasan': 1,
 'singgung': 1,
 'only': 1,
 'layanan': 3,
 'keluasan': 3,
 'langganan': 4,
 'resap': 3,
 'menyingsing': 3,
 'lelap': 4,
 'tembus': 3,
 'keringanan': 2,
 'beterbangan': 2,
 'lipur': 2,
 'sajak': 2,
 'mempertentangkan': 1,
 'peria': 2,
 'respons': 3,
 'jawaban': 3,
 'reaksi': 2,
 'kangen': 3,
 'tlg': 3,
 'sahutan': 1,
 'cepet': 2,
 'doang': 1,
 'lantik': 3,
 'akibat': 1,
 'sambutan': 3,
 'bersalin': 3,
 'wahyu': 4,
 'maha': 4,
 'terlindung': 4,
 'menetap': 3,
 'bersikukuh': 1,
 'rusuhan': 1,
 'meyakinkan': 3,
 'berkukuh': 2,
 'silang selisih': 1,
 'bersiteguh': 1,
 'syg': 3,
 'hii': 3,
 'pencegah': 2,
 'dependen': 3,
 'berteguh hati': 4,
 'berkuat': 3,
 'amin': 3,
 'tersampai': 2,
 'bersyukur': 5,
 'bergeming': 1,
 'jernih (suasana)': 1,
 'nunggu': 1,
 'abis': 1,
 'bertekun': 4,
 'selamat': 5,
 'asmara': 2,
 'bertahan': 4,
 'suka-suka': 3,
 'gapaian': 3,
 'penguasaan': 3,
 'iritasi': 1,
 'mukhlis': 3,
 'senyap': 1,
 'terpukul': 1,
 'elite': 5,
 'asketisme': 2,
 'cita rasa': 3,
 'mampir': 2,
 'pasif': 1,
 'interferensi': 2,
 'membatu': 2,
 'lurus hati': 3,
 'geming': 2,
 'stagnan': 1,
 'membisu': 1,
 'cengkeraman': 1,
 'bungkam': 1,
 'raihan': 2,
 'asik': 4,
 'ready': 1,
 'sepantar': 1,
 'usikan': 1,
 'pantau': 2,
 'tunduk': 1,
 'karena Allah': 2,
 'fans': 2,
 'provokasi': 1,
 'terbaring': 2,
 'zuhud': 2,
 'sporadis': 2,
 'tertulang': 2,
 'capaian': 4,
 'rengkuhan': 1,
 'sukarela': 4,
 'sarannya': 1,
 'pesan': 2,
 'mencintaimu': 4,
 'menutup mulut': 1,
 'tidur': 3,
 'beribadat': 4,
 'meminta (kpd Tuhan)': 3,
 'yoga': 1,
 'sayid': 3,
 'dapet': 2,
 'mendoa': 4,
 'berharap': 4,
 'harap': 3,
 'berdoa': 4,
 'bersembahyang': 5,
 'berselawat': 3,
 'yes': 3,
 'berpasrah': 3,
 'buruan': 1,
 'semi': 2,
 'memanjatkan doa': 4,
 'top': 5,
 'mood': 2,
 'berzikir': 4,
 'kenal': 3,
 'kebahagiaan': 4,
 'dengerin': 3,
 'bertanding': 2,
 'berusaha': 3,
 'jempolan': 4,
 'yahud': 4,
 'berjihad': 3,
 'juang': 3,
 'bersangkut': 1,
 'mencolok': 2,
 'pasar uang': 2,
 'memikat': 2,
 'taut': 2,
 'bayar': 1,
 'menarik': 4,
 'hebring': 3,
 'seru': 5,
 'pukul': 1,
 'simak': 3,
 'memuaskan': 5,
 'aduhai': 4,
 'bergelanggang': 2,
 'hatiku': 2,
 'love': 5,
 'yuuk': 4,
 'pelipuran': 2,
 'profitabel': 4,
 'tebal telinga': 1,
 'senyumin': 3,
 'cuek': 1,
 'berlaba': 4,
 'peduli': 4,
 'insyaallah': 2,
 'berkhasiat': 4,
 'diem': 2,
 'menguntungkan': 4,
 'mulu': 2,
 'motivasi': 3,
 'berkat': 1,
 'apatis': 1,
 'berhikmah': 2,
 'berfaedah': 4,
 'purnama': 2,
 'mengagumkan': 4,
 'siph': 2,
 'inklusif': 1,
 'beneran': 3,
 'wewenang': 2,
 'mojang': 2,
 'lunch': 3,
 'aziz': 2,
 'fav': 5,
 'okay': 4,
 'melancarkan': 3,
 'nemenin': 2,
 'cicip': 3,
 'bunda': 3,
 'laun': 1,
 'waras': 2,
 'pinter': 5,
 'melorot': 1,
 'bilas': 1,
 'terjeblos': 1,
 'terjun': 1,
 'menggelincir': 1,
 'lunas (kapal': 2,
 'rebah': 2,
 'reparasi': 3,
 'gontai': 1,
 'sederhana': 3,
 'tumpuan': 2,
 'himpit': 1,
 'turunan': 1,
 'mudah': 4,
 'tumbang': 1,
 'live': 3,
 'memandu': 3,
 'gamblang': 3,
 'terjungkal': 1,
 'ngasih': 3,
 'penyempurnaan': 3,
 'asasi': 3,
 'gurufavorit': 3,
 'friends': 3,
 'tercemplung': 1,
 'rektifikasi': 1,
 'meringankan': 2,
 'mamak': 2,
 'lambat': 1,
 'memudahkan': 3,
 'terbanting': 1,
 'pencitraan': 2,
 'berikhtiar': 3,
 'belanja': 2,
 'andai': 2,
 'lingsir': 2,
 'murah': 3,
 'assalamualaikum': 3,
 'ibunda': 3,
 'luruh': 2,
 'fondasi': 2,
 'arabika': 2,
 'membayangkan': 2,
 'rekonsiliasi': 4,
 'copot': 1,
 'simbok': 2,
 'saldo': 2,
 'berjatuhan': 1,
 'tergelincir': 1,
 'memuluskan': 3,
 'rontok': 1,
 'islam': 4,
 'mama': 4,
 'filial': 2,
 'ujian': 1,
 'puterin': 1,
 'mengantongi': 1,
 'gugur': 1,
 'berbuah': 2,
 'bersila': 2,
 'inovasi': 4,
 'berumah tangga': 2,
 'berbakat': 4,
 'ngerti': 1,
 'menumpang tinggal': 1,
 'menggelesot': 1,
 'kuliah': 1,
 'berbunga': 3,
 'filsafat': 3,
 'berketurunan': 2,
 'tinggal': 1,
 'wafat': 1,
 'bertunangan': 3,
 'kepo': 2,
 'menongkrong': 1,
 'dimulai': 1,
 'tabungan': 3,
 'kuat (dugaan)': 2,
 'deposito': 3,
 'hy': 1,
 'mewarisi': 3,
 'komedi': 3,
 'fokus': 3,
 'bebodoran': 2,
 'lahir': 3,
 'deket': 1,
 'dewasa': 2,
 'menikah': 4,
 'tekad': 4,
 'bermukim': 2,
 'berpembawaan': 1,
 'pertukaran': 1,
 'dagelan': 3,
 'kasad': 1,
 'kelucuan': 3,
 'keduniaan': 1,
 'tawakal': 3,
 'cash': 2,
 'mengesahkan': 2,
 'pamrih': 1,
 'join': 1,
 'pancaroba': 1,
 'kunjungi': 3,
 'berdaya guna': 4,
 'modifikasi': 2,
 'mengirat': 2,
 'searah': 1,
 'khusyuk': 3,
 'adi': 2,
 'sob': 2,
 'beroperasi': 1,
 'didik': 3,
 'vote': 1,
 'iflix': 1,
 'gratifikasi': 2,
 'pamit': 2,
 'ekstra': 3,
 'bermohon': 3,
 'berdua': 1,
 'angguk': 1,
 'bepergian': 1,
 'joli': 1,
 'jodoh': 3,
 'terkoneksi': 3,
 'herbal': 2,
 'sesuai': 3,
 'sekata': 3,
 'laporkan': 2,
 'penghidupan': 2,
 'utopia': 2,
 'berkenan': 2,
 'rahim': 2,
 'lewat': 2,
 'geleser': 1,
 'special': 4,
 'obsesi': 1,
 'sepakat': 4,
 'bermohon diri': 2,
 'insentif': 3,
 'nafkah': 3,
 'setuju': 4,
 'curhat': 2,
 'berproses': 1,
 'varian': 1,
 'oke': 2,
 'kesabaran': 5,
 'mufakat': 4,
 'rawat': 3,
 'mikir': 2,
 'karunia': 4,
 'beredar': 2,
 'rangkap': 2,
 'tengah': 2,
 'komisi': 3,
 'check': 1,
 'nasi': 2,
 'serasi': 4,
 'maklumat': 2,
 'darurat': 1,
 'disarankan': 1,
 'inisiator': 3,
 'substansial': 1,
 'luntur': 1,
 'trima': 1,
 'berbagi': 2,
 'kabar': 2,
 'tiara': 3,
 'lancar': 4,
 'lanjutkan': 1,
 'baik-baik': 3,
 'pelancar': 2,
 'say': 1,
 'ajak': 1,
 'meminta': 1,
 'publikasi': 2,
 'benar-benar': 2,
 'rasio': 1,
 'baper': 1,
 'intensif': 2,
 'menyembul': 1,
 'hadir': 2,
 'muncul': 1,
 'menukar': 1,
 'ayunan': 3,
 'berhati-hati': 3,
 'kembang-kempis': 3,
 'hastag': 1,
 'diskaun': 3,
 'jumat': 2,
 'babe': 3,
 'merapal': 1,
 'bergetar': 1,
 'mengerubungi': 1,
 'bernyanyi': 2,
 'terperengah': 1,
 'irit': 2,
 'bergema': 1,
 'setir': 1,
 'penggunaan': 1,
 'selidik': 2,
 'penimbunan': 1,
 'muslim': 3,
 'merinai': 1,
 'memindahkan': 1,
 'swagriya': 2,
 'memperhitungkan': 1,
 'lelang': 1,
 'cuat': 2,
 'kenangan': 3,
 'kehebohan': 1,
 'maksimal': 3,
 'dipantau': 2,
 'smartphone': 1,
 'penabung': 3,
 'sharing': 3,
 'tampak': 1,
 'ngerasain': 1,
 'jagalah': 3,
 'penumpukan': 1,
 'lovers': 4,
 'gelegak': 1,
 'nyanyi': 3,
 'bahas': 2,
 'pengembangannya': 3,
 'tertinggi': 3,
 'lenggang': 2,
 'monggo': 3,
 'mengeroyok': 1,
 'ayun': 1,
 'aba': 2,
 'abi': 2,
 'queen': 2,
 'ekonomis': 3,
 'mengangsur': 1,
 'sebenernya': 1,
 'refresh': 2,
 'orang islam': 2,
 'nice': 4,
 'ayahanda': 1,
 'membahas': 1,
 'menorehkan': 1,
 'penambahan': 2,
 'kaitan': 1,
 'menyembur': 1,
 'gesek': 1,
 'geser': 1,
 'tetap hati': 3,
 'tercinta': 4,
 'signifikansi': 2,
 'sidang': 1,
 'penggentaran': 1,
 'definit': 2,
 'jali': 2,
 'kekerabatan': 3,
 'afiliasi': 2,
 'konkret': 3,
 'chat': 3,
 'alim': 2,
 'fanbase': 3,
 'reseptor': 2,
 'maujud': 2,
 'merah jambu': 3,
 'komunitas': 2,
 'eviden': 3,
 'genah': 2,
 'sensibel': 2,
 'coffee': 2,
 'bernyali besar': 3,
 'sangat': 3,
 'goda': 2,
 'sparing': 3,
 'jaringan': 3,
 'real': 2,
 'sentuh': 1,
 'belajar': 3,
 'informasinya': 2,
 'mengaibkan': 1,
 'membiasakan': 2,
 'konfirmasinya': 3,
 'kesimpulan': 3,
 'berwujud': 2,
 'pantas mulut': 2,
 'rizki': 4,
 'latih': 3,
 'sweet': 3,
 'bernyali': 4,
 'kentara': 1,
 'banget': 1,
 'percaya diri': 4,
 'adzan': 3,
 'transparansi': 2,
 'salamat': 4,
 'dear': 2,
 'persangkutan': 2,
 'candang': 2,
 'anut': 2,
 'jalanin': 2,
 'pandai bicara': 3,
 'pancur': 1,
 'interaksi': 3,
 'alim arif': 4,
 'cakep': 5,
 'single': 3,
 'penerima': 2,
 'langgam': 2,
 'merah muda': 3,
 'nyali besar': 3,
 'nekat': 2,
 'kesatria': 2,
 'sungguh-sungguh': 2,
 'konfirmasikan': 3,
 'bentur': 1,
 'determinasi': 3,
 'medium': 2,
 'tampilan': 1,
 'baku': 1,
 'kubra': 2,
 'satria': 4,
 'jentelmen': 3,
 'relevansi': 2,
 'penyambut': 2,
 'faktual': 3,
 'krim': 1,
 'melakoni': 1,
 'jamiah': 1,
 'esok': 1,
 'dikasih': 2,
 'penunggu dunia': 2,
 'ijab': 2,
 'menayangkan': 2,
 'snapback': 2,
 'pinky': 3,
 'sejenak': 1,
 'favorite': 4,
 'sigap': 4,
 'membimbingmu': 3,
 'couple': 2,
 'syarikat': 3,
 'penyesuaian': 3,
 'menghadiahkan': 3,
 'ikat janji': 3,
 'dapatkan': 2,
 'secepatnya': 3,
 'drum': 2,
 'tengkurap': 2,
 'terluang': 2,
 'nada': 2,
 'yukk': 4,
 'berlebih': 1,
 'tempo': 1,
 'hostel': 1,
 'menganugerahi': 3,
 'rembuk': 3,
 'pesanggrahan': 2,
 'pemikiran': 1,
 'bahasan': 1,
 'pose': 3,
 'bertaraf': 3,
 'penangguhan': 3,
 'mobil': 1,
 'care': 2,
 'baju': 2,
 'biarkan': 1,
 'bertekan': 1,
 'adaptasi': 2,
 'melayani': 3,
 'help': 2,
 'konferensi': 2,
 'gerak gerik': 1,
 'menyikap': 1,
 'pingin': 2,
 'lompong': 1,
 'azimat': 1,
 'penyelarasan': 3,
 'hamba Allah': 3,
 'bersemangat': 4,
 'habituasi': 1,
 'layan': 2,
 'ciyeee': 1,
 'senyumnya': 3,
 'maen': 3,
 'meladeni': 3,
 'perbincangan': 2,
 'merenangi': 1,
 'kesepakatan': 3,
 'itihad': 3,
 'menyelami': 3,
 'forum': 2,
 'penginapan': 2,
 'super': 3,
 'menggores': 1,
 'kencan': 3,
 'pengakuan': 2,
 'imbang': 2,
 'duluan': 2,
 'ngobrol': 1,
 'bismillah': 4,
 'tekan': 1,
 'pembahasan': 1,
 'berkualitas': 4,
 'ketiadaan': 1,
 'tandang': 1,
 'kestabilan': 4,
 'mengontak': 1,
 'memarkir': 1,
 'arung': 1,
 'cintai': 4,
 'tayang': 3,
 'balas': 1,
 'enjoy': 3,
 'kuy': 1,
 'motel': 1,
 'tengok': 2,
 'dangkal': 1,
 'deres': 1,
 'menelungkup': 1,
 'mirip': 1,
 'permufakatan': 3,
 'booking': 2,
 'plus': 2,
 'baiknya': 1,
 'meniti': 2,
 'reply': 2,
 'musyawarah': 2,
 'bernas': 2,
 'tambah': 3,
 'losmen': 2,
 'kenek': 1,
 'kerjaan': 2,
 'tukar pikiran': 3,
 'teh': 1,
 ...}

In [22]:
# Membaca data kamus kata-kata negatif dari GitHub
lexicon_negative = dict()

response = requests.get(
    "https://raw.githubusercontent.com/angelmetanosaa/dataset/main/lexicon_negative.csv"
)
# Mengirim permintaan HTTP untuk mendapatkan file CSV dari GitHub
response

In [23]:
if (response.status_code == 200):
    reader = csv.reader(StringIO(response.text), delimiter=",")
    lexicon_negative = {row[0]: int(row[1]) for row in reader}
else:
    print("Failed to fetch negative lexicon data")

lexicon_negative

{'putus tali gantung': -2,
 'gelebah': -2,
 'gobar hati': -2,
 'tersentuh (perasaan)': -1,
 'isak': -5,
 'larat hati': -3,
 'nelangsa': -3,
 'remuk redam': -5,
 'tidak segan': -2,
 'gemar': -1,
 'tak segan': -1,
 'sesal': -4,
 'pengen': -2,
 'penghayatan': -2,
 'absorpsi': -1,
 'linu': -4,
 'salah benang': -1,
 'sakit': -5,
 'lara': -5,
 'zuhud': -1,
 'mencederai': -4,
 'mengingkari': -4,
 'maaf': -3,
 'mengkhianat': -4,
 'mencelakai': -5,
 'mulu': -1,
 'ngga': -2,
 'borong': -1,
 'lever': -2,
 'kasian': -3,
 'gamau': -4,
 'doang': -1,
 'pulas': -1,
 'abis': -2,
 'coba': -1,
 'kangen': -3,
 'kalau': -1,
 'maunya': -1,
 'seandainya': -1,
 'marilah': -1,
 'bener': -1,
 'yaudah': -4,
 'nggak': -3,
 'gatau': -1,
 'apaan': -4,
 'ngakak': -2,
 'atuh': -1,
 'sekali': -1,
 'menarik hati': -1,
 'cedayam': -2,
 'kece': -3,
 'termakan': -1,
 'belom': -1,
 'malem': -1,
 'mencekau': -2,
 'menduga': -1,
 'menyuarakan': -1,
 'memprediksi': -1,
 'membunyikan': -1,
 'menerka': -1,
 'menaksir': -1,
 'mengantisipasi': -1,
 'nangis': -5,
 'rompok': -2,
 'soalnya': -1,
 'griya': -1,
 'gubuk': -2,
 'anjir': -3,
 'putus jiwa': -5,
 'berlalu dr dunia': -5,
 'putus nyawa': -5,
 'menarik napas penghabisan': -5,
 'membuang nyawa': -5,
 'hilang hayat': -4,
 'putus napas': -4,
 'kojor': -3,
 'berputih tulang': -2,
 'buntu': -3,
 'berkalang tanah': -2,
 'koit': -5,
 'putus usia': -3,
 'buntet': -2,
 'tamat riwayatnya': -3,
 'menamatkan riwayatnya': -3,
 'hilang nyawa': -5,
 'males': -4,
 'asih': -1,
 'kasih sayang': -1,
 'kekaguman': -1,
 'dendam berahi': -4,
 'rindu': -3,
 'afeksi': -2,
 'cinta kasih': -1,
 'renjana': -2,
 'pagina': -2,
 'tresna': -1,
 'filantropi': -1,
 'cintrong': -1,
 'cetusan': -1,
 'katanya': -1,
 'rintisan': -2,
 'kronologi': -1,
 'jalan buntu': -4,
 'rintis': -2,
 'jalan bebas hambatan': -1,
 'purwa': -2,
 'lanjut umur': -3,
 'bangkot': -4,
 'sepuh': -3,
 'lanjut usia': -3,
 'lepra': -5,
 'bau tanah': -4,
 'berumur': -2,
 'purba': -3,
 'jomblo': -3,
 'gacoan': -2,
 'tambatan hati': -2,
 'sir-siran': -2,
 'malam': -1,
 'tayib': -1,
 'tayibah': -1,
 'necis': -1,
 'estetis': -1,
 'baper': -4,
 'perfek': -1,
 'tolong': -2,
 'sayid': -1,
 'radang': -4,
 'didih': -4,
 'ngantuk': -2,
 'sirap hati': -2,
 'rampang': -2,
 'kecil hati': -4,
 'bertelinga merah': -3,
 'tersirap hatinya': -2,
 'merah telinga': -3,
 'mencak-mencak': -5,
 'gaada': -3,
 'manjur': -1,
 'mujarab': -1,
 'beber': -2,
 'singkap': -3,
 'penangkis': -3,
 'mending': -3,
 'akibat': -3,
 'satir': -2,
 'nyanyian': -2,
 'menyibuk': -2,
 'gara': -4,
 'dikit': -4,
 'ilang': -5,
 'kepeng': -2,
 'bodo': -5,
 'air': -1,
 'suri': -1,
 'ihh': -5,
 'asasi': -3,
 'menenes': -2,
 'tumpuan': -3,
 'fondasi': -3,
 'beliin': -1,
 'sekam': -3,
 'maafin': -3,
 'memahirkan': -1,
 'menggalakkan memanas-manasi': -3,
 'ngambek': -5,
 'ampun': -3,
 'terbalik akal': -4,
 'tidak masuk akal': -4,
 'gangguan jiwa': -4,
 'majenun': -2,
 'gelo': -2,
 'gila-gila': -4,
 'kalap': -3,
 'sedeng': -2,
 'berubah akal': -2,
 'serem': -5,
 'terlalu': -3,
 'sakit jiwa': -4,
 'gendeng': -2,
 'berubah ingatan': -3,
 'sinting': -5,
 'gila': -5,
 'sakit ingatan': -4,
 'sesat akal': -2,
 'duh': -4,
 'emg': -1,
 'hujan': -2,
 'aduh': -3,
 'cerita khayal': -2,
 'typo': -2,
 'langkah baik': -1,
 'isapan jempol': -3,
 'engah': -4,
 'mafhum': -1,
 'fiksi': -2,
 'omong kosong': -4,
 'bales': -3,
 'profit': -1,
 'waris': -2,
 'selisih': -4,
 'senjang': -4,
 'bareng': -3,
 'ekstasi': -3,
 'laper': -3,
 'hendaknya': -1,
 'membandel': -5,
 'ngaku': -3,
 'kiranya': -1,
 'telat': -5,
 'kopong': -4,
 'ngerti': -1,
 'keduniaan': -2,
 'nol': -3,
 'nyari': -2,
 'sorry': -4,
 'peranakan': -3,
 'bastar': -2,
 'tega': -5,
 'berdenyut': -3,
 'kayaknya': -3,
 'sibuk': -3,
 'ringan tangan': -1,
 'bergelora': -2,
 'sampai rasa': -2,
 'energik': -1,
 'membara': -3,
 'berkobar-kobar': -2,
 'menyala': -2,
 'mentolo': -2,
 'sampai hati': -2,
 'bersungguh-sungguh': -1,
 'tren': -2,
 'menyembur': -3,
 'imbas': -4,
 'aliran udara': -1,
 'melesit': -1,
 'rahayu': -2,
 'kemungkinan': -1,
 'menggusari': -3,
 'mencurat': -1,
 'memarahi': -5,
 'topan': -3,
 'tembis': -3,
 'mendamprat': -4,
 'suak': -2,
 'bongsor': -2,
 'bias': -2,
 'rajaman': -4,
 'rantus': -3,
 'gentas': -2,
 'nanya': -1,
 'melelah': -3,
 'bosen': -4,
 'maksudnya': -1,
 'bersusah hati': -5,
 'berkabung': -5,
 'receh': -4,
 'bermuram durja': -5,
 'pls': -3,
 'berlara-lara': -4,
 'opp': -1,
 'seneng': -1,
 'bersungkawa': -3,
 'bersusah': -5,
 'peluk': -3,
 'tt': -2,
 'menepis': -3,
 'obsesi': -2,
 'dekap': -2,
 'gausah': -4,
 'sengsara': -5,
 'buru-buru': -3,
 'kencang': -3,
 'kilat': -2,
 'begini': -1,
 'akas': -2,
 'mendahului': -1,
 'mengadang': -3,
 'suruh': -2,
 'terampil': -3,
 'pesat': -2,
 'sebat': -3,
 'sput': -2,
 'filsafat': -3,
 'dogma': -3,
 'imut': -1,
 'doktrin': -3,
 'lapar': -5,
 'dominan': -2,
 'masif': -3,
 'keliatan': -1,
 'keras tulang': -2,
 'tangguh': -2,
 'keseser': -4,
 'maksa': -5,
 'bertanduk': -2,
 'luput': -3,
 'jaman': -2,
 'menggeliat': -3,
 'tumpas': -4,
 'keok': -2,
 'tercecer': -3,
 'beterbangan': -3,
 'berpengaruh': -2,
 'lipur': -2,
 'bedegap': -2,
 'besar lengan': -2,
 'gelibat': -2,
 'suka cita': -1,
 'pacaran': -3,
 'bersemangat': -1,
 'berbahagia': -1,
 'berdesir': -2,
 'tersuntuk': -4,
 'adek': -1,
 'block': -4,
 'pening': -3,
 'apanya': -3,
 'kliyengan': -4,
 'pusing': -4,
 'jenguk': -2,
 'akunya': -1,
 'runyam': -5,
 'luyu': -1,
 'mikir': -3,
 'elusif': -2,
 'kuat (dugaan)': -2,
 'memihak': -3,
 'boong': -4,
 'tandang': -2,
 'kesian': -3,
 'sayu': -3,
 'cenderung': -2,
 'selit-belit': -3,
 'preseden': -2,
 'miss': -4,
 'napa': -2,
 'ikutan': -3,
 'baik-baik': -1,
 'kesel': -5,
 'intensif': -4,
 'closed': -3,
 'maap': -3,
 'maafkan': -3,
 'kalem': -2,
 'ndak': -3,
 'rantaian': -3,
 'pinter': -1,
 'mesti': -3,
 'diserang': -4,
 'benak kepala': -3,
 'otak': -3,
 'daya pikir': -2,
 'wajib': -2,
 'dedengkot': -2,
 'ketagihan': -3,
 'bogem mentah': -5,
 'gila-gilaan': -3,
 'nanti': -2,
 'coretan': -1,
 'sebenernya': -1,
 'halah': -5,
 'alay': -4,
 'gergaji': -1,
 'kemasukan': -3,
 'berbayar': -3,
 'tukang': -2,
 'memotong': -3,
 'bayar': -3,
 'curhat': -3,
 'beri (uang)': -2,
 'kesusupan': -2,
 'pakar': -1,
 'kawaei': -2,
 'kebabaran': -2,
 'berjatuhan': -3,
 'runtuh': -5,
 'terperenyak': -4,
 'penggentaran': -4,
 'tanya': -2,
 'pailit': -5,
 'tersingkir': -5,
 'melorot': -4,
 'menetes': -3,
 'roboh': -5,
 'tercebur': -5,
 'membiak': -3,
 'terjeblos': -4,
 'menggelincir': -3,
 'rebah': -3,
 'nyesel': -5,
 'biasin': -3,
 'terjun': -3,
 'perusuhan': -4,
 'kedapatan': -2,
 'tertangkap tangan': -4,
 'terpelanting': -3,
 'melubangi': -3,
 'tercemplung': -4,
 'jeblos': -4,
 'diem': -3,
 'tepergok': -5,
 'kayanya': -2,
 'terbanting': -3,
 'tertangkap basah': -3,
 'membabar': -1,
 'terjerembab': -2,
 'luruh': -2,
 'tergelincir': -3,
 'terbuang': -2,
 'berhenti (tugas)': -2,
 'gogrok': -3,
 'jelabak': -3,
 'menyembul': -3,
 'cape': -4,
 'cuat': -3,
 'unjuk': -3,
 'menyongsong': -2,
 'kesebalikan': -2,
 'sekutu': -3,
 'kekang': -4,
 'mengelukan': -2,
 'berasa': -2,
 'temenan': -2,
 'purnama': -3,
 'ekstrem': -4,
 'pendahuluan': -1,
 'inklusif': -2,
 'kebaca': -1,
 'revolusioner': -1,
 'asak': -3,
 'lelang': -3,
 'permulaan': -3,
 'radikal': -4,
 'berjejal': -3,
 'begah': -2,
 'telak': -3,
 'telik': -2,
 'hati-hati': -3,
 'ingat-ingat': -3,
 'jaga-jaga': -3,
 'entah-berentah': -3,
 'tajam mata': -1,
 'kelih': -3,
 'please': -3,
 'tae': -4,
 'awas': -3,
 'si dia': -3,
 'gaboleh': -4,
 'denger': -3,
 'disuruh': -2,
 'waspada': -3,
 'entah': -3,
 'pelit': -5,
 'kial': -4,
 'nemu': -2,
 'kroni': -3,
 'bot': -2,
 'cute': -1,
 'rekan': -2,
 'sepihak': -3,
 'wacana': -3,
 'tengok': -2,
 'subang': -1,
 'komplot': -4,
 'giwang': -1,
 'melendeh': -3,
 'bersimpuh': -3,
 'mengogah': -3,
 'menggelesot': -3,
 'menumpang tinggal': -4,
 'kuliah': -2,
 'bulan': -1,
 'bersemayam': -3,
 'ampas (kopi)': -2,
 'menikah': -2,
 'manja': -3,
 'polos': -2,
 'bercokol': -4,
 'cokol': -4,
 'sia': -5,
 'esok': -2,
 'maneh': -3,
 'himpit': -4,
 'tindas': -5,
 'pilih': -2,
 'ngasih': -2,
 'kehebohan': -3,
 'pilih-pilih': -3,
 'bete': -5,
 'payudara': -3,
 'man': -1,
 'tetek': -4,
 'keonaran': -5,
 'buah dada': -3,
 'biarin': -3,
 'kegemparan': -4,
 'dempet': -3,
 'sebel': -5,
 'ucap': -2,
 'bergas': -2,
 'bergadang': -4,
 'kawal': -2,
 'berpengalaman': -1,
 'sadar': -1,
 'dukacarita': -4,
 'apasih': -4,
 'gugah': -1,
 'bertindik': -3,
 'drama duka': -4,
 'pindah': -3,
 'oma': -2,
 'penderitaan': -5,
 'menugaskan': -1,
 'asri': -3,
 'borak': -4,
 'kepedihan': -5,
 'pulak': -2,
 'menyunduk': -3,
 'rawat': -3,
 'buyut': -3,
 'tragedi': -5,
 'kecek': -3,
 'andal': -1,
 'kesialan': -5,
 'kismat': -2,
 'daya muat': -2,
 'mengamuk': -5,
 'suratan takdir': -3,
 'kemalangan': -5,
 'kegeruhan': -4,
 'iyain': -2,
 'dikatain': -3,
 'duluan': -2,
 'pokoknya': -3,
 'daya tampung': -2,
 'daya serap': -2,
 'kenahasan': -2,
 'keberuntungan': -1,
 'bahala': -3,
 'gerhana': -2,
 'sedi': -2,
 'bersengaja': -2,
 'segitu': -3,
 'php': -4,
 'fk': -4,
 'tendas': -4,
 'dikira': -3,
 'gabut': -5,
 'statis': -3,
 'pasif': -3,
 'membatu': -2,
 'hiatus': -2,
 'stagnan': -3,
 'membisu': -3,
 'membiarkan': -3,
 'gasuka': -4,
 'lepaskan': -2,
 'rasa': -2,
 'huhuhu': -2,
 'bungkam': -4,
 'kosong': -4,
 'bajing': -5,
 'rasa hati': -2,
 'mendiamkan': -3,
 'tertegun': -3,
 'kaget': -3,
 'cabe': -2,
 'sugesti': -3,
 'kuota': -2,
 'lengang': -4,
 'tengkulak': -5,
 'campakkan': -4,
 'syur': -3,
 'bersanggama': -2,
 'sepi': -3,
 'naon': -2,
 'berteduh': -2,
 'mematung': -3,
 'keluarkan': -3,
 'memaafkan': -3,
 'menutup mulut': -3,
 'terperanjat': -3,
 'melanyak': -3,
 'menghinakan': -5,
 'melancarkan': -2,
 'menistakan': -5,
 'leave': -3,
 'melicinkan': -2,
 'murah': -2,
 'spam': -3,
 'mentang': -3,
 'kepo': -3,
 'tobat': -2,
 'mentang-mentang': -4,
 'meringankan': -1,
 'astagfirullah': -4,
 'memudahkan': -1,
 'titip api': -1,
 'mencebikkan': -3,
 'fokus': -2,
 'menahankan': -2,
 'resistan': -2,
 'mengentengkan': -2,
 'astaga': -4,
 'maapin': -4,
 'berat tangan': -4,
 'berat hati': -4,
 'lembam': -4,
 'macem': -2,
 'realitas': -3,
 'alpa': -3,
 'yauda': -4,
 'gigit': -2,
 'ihhh': -4,
 'sorang': -2,
 'berat pinggul': -2,
 'merasa': -2,
 'milih': -2,
 'kerubut': -3,
 'penyebab': -3,
 'kempes': -4,
 'bye': -3,
 'mengerubungi': -3,
 'bertuntun': -2,
 'ketauan': -4,
 'serah': -3,
 'wabah': -5,
 'uar-uar': -3,
 'wara-wara': -3,
 'mengeroyok': -4,
 'istirahat': -2,
 'gajadi': -3,
 'dirimu': -1,
 'ati': -1,
 'love': -3,
 'ngerasa': -2,
 'jelus': -2,
 'timbalan': -2,
 'dajal': -5,
 'artistik': -2,
 'mukhlis': -2,
 'tentangan': -2,
 'mbeling': -2,
 'rame': -2,
 'iri': -5,
 'ngeselin': -5,
 'ngatain': -5,
 'ganjaran': -5,
 'junjungan': -2,
 'imut-imut': -1,
 'seruh': -2,
 'lurus hati': -1,
 'lari-lari': -2,
 'senyum': -1,
 'seringai': -4,
 'mengganjar': -3,
 'panas hati': -5,
 'keki': -4,
 'jail': -4,
 'lemot': -5,
 'sayangnya': -3,
 'menghukum': -3,
 'bukannya': -3,
 'disayang': -3,
 'memberi': -2,
 'membalas': -3,
 'gemes': -2,
 'sukarela': -2,
 'kebiri': -4,
 'berprasangka': -3,
 'pahala': -1,
 'pemudaan': -1,
 'mohon': -2,
 'terhenti': -3,
 'erang': -4,
 'manah': -2,
 'mabok': -4,
 'dipanggil': -1,
 'mager': -4,
 'kepedulian': -2,
 'item': -4,
 'rip': -5,
 'membandungi': -1,
 'haih': -4,
 'muda': -2,
 'tuhkan': -4,
 'memperduakan': -3,
 'regenerasi': -2,
 'gubrisan': -2,
 'pengindahan': -2,
 'ribet': -4,
 'master': -1,
 'tetap hati': -1,
 'tertanggung': -4,
 'diapain': -3,
 'kira': -2,
 'pelita': -2,
 'bernyali': -2,
 'tangan panas': -4,
 'merugi': -5,
 'bernyali besar': -1,
 'meninggal': -4,
 'ngerjain': -2,
 'puntung': -3,
 'percuma': -4,
 'percaya diri': -1,
 'pikir': -2,
 'merah': -3,
 'nyali besar': -2,
 'nekat': -4,
 'njir': -3,
 'dipaksa': -4,
 'pembaiatan': -3,
 'satria': -1,
 'masak': -2,
 'labil': -4,
 'goreng': -2,
 'antipati': -3,
 'kontradiksi': -3,
 'apalah': -2,
 'ditinggal': -4,
 'temenin': -3,
 'kerumitan': -5,
 'khilaf': -4,
 'nihh': -3,
 'selidik': -3,
 'mewajibkan': -2,
 'lagian': -3,
 'negasi': -2,
 'meh': -5,
 'kota': -1,
 'varian': -2,
 'semi': -2,
 'memperkeruh': -4,
 'mencolong': -5,
 'kekusutan': -4,
 'rudapaksa': -4,
 'telaah': -2,
 'keruwetan': -4,
 'sedihnya': -5,
 'teledor': -5,
 'hatiku': -2,
 'kot': -1,
 'terserah': -3,
 'terlanjur': -3,
 'cakep': -1,
 'tergeleng-geleng': -3,
 'sepertinya': -2,
 'kagak': -3,
 'tercengang': -2,
 'permenungan': -3,
 'cengang': -3,
 'mencinta': -1,
 'menyesal': -4,
 'lumayan': -2,
 'matanya': -2,
 'berduka': -5,
 'atraktif': -2,
 'pamer': -3,
 'pucat': -4,
 'terpesona': -1,
 'banjir': -4,
 'takjub': -1,
 'terpana': -2,
 'bah': -3,
 'terkesima': -1,
 'menakjubkan': -1,
 'memukau': -1,
 'impas': -3,
 'menakjubi': -1,
 'bandang': -4,
 'terpukau': -1,
 'tiada': -5,
 'rasisme': -5,
 'memesonakan': -1,
 'sirik': -5,
 'mengherankan': -3,
 'bersesal': -4,
 'gapernah': -3,
 'rapi': -2,
 'bertanya-tanya': -3,
 'penasaran': -3,
 'tulus hati': -1,
 'beton': -2,
 'menunggui': -3,
 'umpan': -3,
 'cadas': -3,
 'lembek': -4,
 'hih': -4,
 'menutup': -3,
 'korban': -4,
 'kurban': -3,
 'sikit': -3,
 'mengawal': -2,
 'peduli': -1,
 'bongkah': -2,
 'bodoamat': -4,
 'rela': -3,
 'dengkik': -4,
 'takda': -2,
 'obat': -3,
 'tetua': -2,
 'error': -5,
 'anugerah': -1,
 'dongeng': -1,
 'jir': -3,
 'batas (waktu)': -3,
 'impoten': -5,
 'kiri': -3,
 'perih': -4,
 'babi': -4,
 'habitat': -2,
 'kenang-kenangan': -2,
 'reka': -2,
 'memejahijaukan': -4,
 'persembahan': -2,
 'penangguhan': -2,
 'penyudah': -2,
 'gebetan': -2,
 'jutek': -5,
 'ajal': -4,
 'pengakuan': -3,
 'gerombolan': -4,
 'ora': -3,
 'gatel': -3,
 'ketajaman': -2,
 'mencuru': -3,
 'nongol': -2,
 'barzakh': -4,
 'menyidangkan': -3,
 'pantes': -3,
 'ngalah': -3,
 'pejabat': -3,
 'keganjilan': -4,
 'ketidaktentuan': -5,
 'menjaraki': -3,
 'sad': -4,
 'comeback': -2,
 'udahan': -4,
 'ugh': -4,
 'acuh tak acuh': -3,
 'next': -2,
 'penutup': -3,
 'menjenguk': -4,
 'cuek': -5,
 'sangkut-paut': -4,
 'sayup': -3,
 'ish': -4,
 'doh': -4,
 'pantat': -3,
 'tebal telinga': -3,
 'keanehan': -4,
 'mengorek-ngorek': -4,
 'diet': -3,
 'syedih': -5,
 'lugu': -2,
 'interaksi': -2,
 'berhala': -4,
 'kesudahan': -3,
 'iih': -5,
 'tai': -5,
 'kemaknagandaan': -3,
 'masa bodoh': -4,
 'final': -2,
 'dimarahin': -5,
 'nyuruh': -3,
 'dibales': -3,
 'persangkutan': -4,
 'kampret': -5,
 'beristirahat': -2,
 'jin': -3,
 'mikirin': -3,
 'murtad': -5,
 'mogok': -5,
 'setan': -4,
 'nyebut': -3,
 'piye': -3,
 'gusur': -5,
 'drastis': -4,
 'memojokkan': -4,
 'mencengangkan': -3,
 'penunggu': -2,
 'demon': -3,
 'durhaka': -5,
 'super': -2,
 'kesal': -5,
 'iblis': -4,
 'baperan': -4,
 'ngikutin': -2,
 'sebentar': -2,
 'mengerikan': -4,
 'hantu': -4,
 'makhluk halus': -4,
 'got': -3,
 'diam': -3,
 'bunuh': -5,
 'siluman': -5,
 'tumpahan hati': -3,
 'momok': -4,
 'berantem': -4,
 'mangkas': -2,
 'belain': -2,
 'sundal bolong': -5,
 'nahan': -3,
 'sian': -3,
 'jahil': -4,
 'singgah': -2,
 'bersekongkol': -4,
 'life': -2,
 'bidah': -3,
 'menantang': -4,
 'berselingkuh': -5,
 'bergetar': -3,
 'bohong': -5,
 'classy': -2,
 'peristiwa': -2,
 'melumatkan': -4,
 'insiden': -4,
 'oon': -5,
 'orok': -3,
 'selingkuh': -5,
 'nungguin': -2,
 'bijih': -3,
 'pelosot': -3,
 'meremukkan': -4,
 'keburu': -3,
 'gadai': -3,
 'meruntuhkan': -4,
 'anjing': -4,
 'naena': -2,
 'jabang bayi': -3,
 'membinasakan': -5,
 'berdalih': -4,
 'why': -2,
 'modus': -3,
 'waduh': -3,
 'cuti': -2,
 'bobrok': -5,
 'tidurin': -2,
 'cariin': -2,
 'mengandut': -3,
 'berdengung': -3,
 'bakar': -3,
 'mengganyang': -4,
 'merusakkan': -4,
 'menyelusur': -3,
 'berkonspirasi': -4,
 'kurus': -3,
 'berantak': -4,
 'bully': -5,
 'berkomplot': -4,
 'kejadian': -2,
 'ngomongin': -3,
 'stalk': -4,
 'meruntuh': -4,
 'jeriji': -4,
 'memasuki': -3,
 'sange': -5,
 'berkongkalikong': -4,
 'serong': -4,
 'makian': -5,
 'cemong': -4,
 'kerasan': -2,
 'kekurangan': -3,
 'lilit': -3,
 'hinaan': -5,
 'penghinaan': -5,
 'kurung': -3,
 'mengecilkan': -3,
 'cemooh': -5,
 'malu': -4,
 'mengumpat': -4,
 'terabai': -3,
 'mencemooh': -5,
 'merem': -2,
 'lock': -2,
 'melecehkan': -5,
 'kelemahan': -4,
 'kejelekan': -5,
 'ngilang': -3,
 'berkerak': -2,
 'kedaifan': -3,
 'kehinaan keaiban': -4,
 'kontras': -3,
 'mengejek': -4,
 'perang': -3,
 'perundungan': -4,
 'marahin': -4,
 'berkelakar': -4,
 'menyakiti': -5,
 'penyepelean': -4,
 'pait': -4,
 'ngertiin': -3,
 'kecabulan': -5,
 'menjijikkan': -5,
 'tuak': -3,
 'tauu': -3,
 'perbedaan': -2,
 ...}

In [24]:
def sentiment_analysis_lexicon_indonesia(text):
    score = 0

    for word in text:
        if word in lexicon_positive:
            score = score + lexicon_positive[word]

    for word in text:
        if word in lexicon_negative:
            score = score + lexicon_negative[word]

    polarity = ""

    if score > 0:
        polarity = "postive"
    elif score < 0:
        polarity = "negative"
    else:
        polarity = "neutral"
    return score, polarity

In [25]:
df_clean["Label"] = df_clean.apply(lambda x: sentiment_analysis_lexicon_indonesia(x["stemmed"]), axis=1)

In [26]:
df_clean.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,text_lowercase,text_clean,token,stemmed,Label
4,75ff1320-d876-499c-9543-fe80999f9783,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"game jelek, gak recomended, sinyal Wifi diruma...",1,3,2.1.95.12053,2026-08-17 14:40:15,"Halo Kak,\nMaaf atas masalah jaringan yang Kak...",2026-08-17 16:17:22,2.1.95.12053,"game jelek, gak recomended, sinyal wifi diruma...",game jelek recomended sinyal wifi dirumah bagu...,"[game, jelek, recomended, sinyal, wifi, diruma...","[game, jelek, recomended, sinyal, wifi, rumah,...","(-16, negative)"
15,13acfa6f-791b-43c2-80c4-a8bf6876d4af,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Sistem apaan ini?? setim dengan player rank le...,1,28,2.1.95.12053,2026-08-16 03:00:37,"Halo Kak,\nKami berkomitmen untuk menciptakan ...",2026-06-04 10:49:25,2.1.95.12053,sistem apaan ini?? setim dengan player rank le...,sistem setim player rank gw main cover tim fig...,"[sistem, setim, player, rank, gw, main, cover,...","[sistem, tim, player, rank, gw, main, cover, t...","(-10, negative)"
16,04790e53-887b-41c5-9c42-529c0bb79191,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Saya mengajukan keberatan atas dugaan pengguna...,1,4,2.1.95.12053,2026-08-19 08:16:08,"Halo Kak,\nKami berkomitmen untuk menciptakan ...",2026-08-19 10:49:54,2.1.95.12053,saya mengajukan keberatan atas dugaan pengguna...,mengajukan keberatan dugaan penggunaan ai trai...,"[mengajukan, keberatan, dugaan, penggunaan, ai...","[aju, berat, duga, guna, ai, trainingbot, matc...","(-2, negative)"
17,195e4bc2-e0dc-4621-9ad3-fb7dfa362d50,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,tolong fitur highlight nya dibikin otomatis te...,2,3,2.1.95.12053,2026-08-20 10:41:19,"Halo Kak,\nKami mohon maaf atas pengalaman kur...",2026-08-20 14:58:57,2.1.95.12053,tolong fitur highlight nya dibikin otomatis te...,tolong fitur highlight dibikin otomatis tersim...,"[tolong, fitur, highlight, dibikin, otomatis, ...","[tolong, fitur, highlight, bikin, otomatis, si...","(7, postive)"
33,a6f5fb8c-3d10-4dbf-b185-cbffe249546d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"tolong banget ya, kenapa ini banyak komputer a...",1,2,2.1.95.12053,2026-08-21 02:17:47,"Halo Kak,\nKami mohon maaf atas pengalaman kur...",2026-08-21 11:28:44,2.1.95.12053,"tolong banget ya, kenapa ini banyak komputer a...",tolong banget komputer ai rank honor main solo...,"[tolong, banget, komputer, ai, rank, honor, ma...","[tolong, banget, komputer, ai, rank, honor, ma...","(-4, negative)"

# 5.Feature Extraction
**Term Frequency-Inverse Document Frequency**

In [27]:
# TF-IDF
tfidfvec = TfidfVectorizer()
df_clean["stemmed"].iloc[0]
X = df_clean["stemmed"].apply(" ".join)
y = df_clean["Label"].apply(lambda x: x[1])

# X data
X_tfidf = tfidfvec.fit_transform(X)
features_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidfvec.get_feature_names_out())
features_df

,aaaaaaaaaaaahhhhhh,aaaaaaampas,aaaaaahhh,aaaaahh,aaah,aaahhh,aaamiiin,aaamiiinn,aaja,aakn,...,zilonk,zipaul,zize,zodiak,zona,zong,zoning,zonk,zuxin,zzz
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17584,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17585,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17586,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17587,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17588,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

<!-- **Word2Vector** -->

In [28]:
tokenize_data = df_clean["stemmed"];
model = Word2Vec(sentences=tokenize_data, vector_size=100, window=5, min_count=1, workers=4)

X_w2v = np.array([np.mean([model.wv[word] for word in words if word in model.wv],axis=0) for words in tokenize_data])

print(X_w2v.shape)

(17589, 100)

# 6.Modeling

In [29]:
schema_1 = int(len(df_clean) * 0.8) # skema 1: (80% : 20%)
schema_2 = int(len(df_clean) * 0.7) # skema 2: (70% : 30%)

# Splitting data X_tfidf skema 1: (80% : 20%)
X_tfidf_train_1 = X_tfidf[:schema_1]
X_tfidf_test_1 = X_tfidf[schema_1:]
y_train_1 = y.iloc[:schema_1]
y_test_1 = y.iloc[schema_1:]

# Splitting data X_tfidf skema 1: (70% : 30%)
X_tfidf_train_2 = X_tfidf[:schema_2]
X_tfidf_test_2 = X_tfidf[schema_2:]
y_train_2 = y[:schema_2]
y_test_2 = y[schema_2:]

In [30]:
# Splitting data X_w2v skema 1: (80% : 20%)
X_w2v_train_1 = X_w2v[:schema_1]
X_w2v_test_1 = X_w2v[schema_1:]

# Splitting data X_w2v skema 2: (70% : 30%)
X_w2v_train_2 = X_w2v[:schema_2]
X_w2v_test_2 = X_w2v[schema_2:]

**SVM dengan TF-IDF (80/20)**

In [31]:
from sklearn.linear_model import SGDClassifier

svm_1 = SGDClassifier(loss="hinge", random_state=42).fit(X_tfidf_train_1, y_train_1)

y_pred_train_svm_1 = svm_1.predict(X_tfidf_train_1)
y_pred_test_svm_1 = svm_1.predict(X_tfidf_test_1)

accuracy_train_svm_1 = accuracy_score(y_pred_train_svm_1, y_train_1)
accuracy_test_svm_1 = accuracy_score(y_pred_test_svm_1, y_test_1)

print("SVM - accuracy_train_schema_1:", accuracy_train_svm_1)
print("SVM - accuracy_test_schema_1:", accuracy_test_svm_1)

SVM - accuracy_train_schema_1: 0.9360386610759719
SVM - accuracy_test_schema_1: 0.8712336554860717

In [32]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_1, y_pred_test_svm_1, target_names=["negative", "neutral", "positive"]
    )
)

              precision    recall  f1-score   support

    negative       0.87      0.98      0.92      2169
     neutral       0.00      0.00      0.00       249
    positive       0.88      0.86      0.87      1100

    accuracy                           0.87      3518
   macro avg       0.58      0.61      0.60      3518
weighted avg       0.81      0.87      0.84      3518

d:\Machine Learning\Belajar_Fundamental_Deep_Learning\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Machine Learning\Belajar_Fundamental_Deep_Learning\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Machine Learning\Belajar_Fundamental_Deep_Learning\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

**SVM dengan TF-IDF (70/30)**

In [33]:
from sklearn.linear_model import SGDClassifier

svm_2 = SGDClassifier(loss="hinge", random_state=42).fit(X_tfidf_train_2, y_train_2)

y_pred_train_svm_2 = svm_2.predict(X_tfidf_train_2)
y_pred_test_svm_2 = svm_2.predict(X_tfidf_test_2)

accuracy_train_svm_2 = accuracy_score(y_pred_train_svm_2, y_train_2)
accuracy_test_svm_2 = accuracy_score(y_pred_test_svm_2, y_test_2)

print("SVM - accuracy_train_schema_2:", accuracy_train_svm_2)
print("SVM - accuracy_test_schema_2:", accuracy_test_svm_2)

SVM - accuracy_train_schema_2: 0.9428200129954516
SVM - accuracy_test_schema_2: 0.8645063483039606

In [34]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_2, y_pred_test_svm_2, target_names=["negative", "neutral", "positive"]
    )
)

              precision    recall  f1-score   support

    negative       0.86      0.97      0.91      3315
     neutral       0.00      0.00      0.00       388
    positive       0.86      0.86      0.86      1574

    accuracy                           0.86      5277
   macro avg       0.58      0.61      0.59      5277
weighted avg       0.80      0.86      0.83      5277

d:\Machine Learning\Belajar_Fundamental_Deep_Learning\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Machine Learning\Belajar_Fundamental_Deep_Learning\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Machine Learning\Belajar_Fundamental_Deep_Learning\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

**SVM dengan Word2Vector (80/20)**

In [35]:
from sklearn.linear_model import SGDClassifier

svm_3 = SGDClassifier(loss="hinge", random_state=42).fit(X_w2v_train_1, y_train_1)

y_pred_train_svm_3 = svm_3.predict(X_w2v_train_1)
y_pred_test_svm_3 = svm_3.predict(X_w2v_test_1)

accuracy_train_svm_3 = accuracy_score(y_pred_train_svm_3, y_train_1)
accuracy_test_svm_3 = accuracy_score(y_pred_test_svm_3, y_test_1)

print("SVM - accuracy_train_schema_1:", accuracy_train_svm_3)
print("SVM - accuracy_test_schema_1:", accuracy_test_svm_3)

SVM - accuracy_train_schema_1: 0.7668964536990974
SVM - accuracy_test_schema_1: 0.7316657191586129

In [36]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_1, y_pred_test_svm_3, target_names=["negative", "neutral", "positive"]
    )
)

              precision    recall  f1-score   support

    negative       0.76      0.88      0.82      2169
     neutral       1.00      0.01      0.02       249
    positive       0.65      0.61      0.63      1100

    accuracy                           0.73      3518
   macro avg       0.81      0.50      0.49      3518
weighted avg       0.75      0.73      0.70      3518

**SVM dengan Word2Vector (70/30)**

In [37]:
from sklearn.linear_model import SGDClassifier

svm_4 = SGDClassifier(loss="hinge", random_state=42).fit(X_w2v_train_2, y_train_2)

y_pred_train_svm_4 = svm_4.predict(X_w2v_train_2)
y_pred_test_svm_4 = svm_4.predict(X_w2v_test_2)

accuracy_train_svm_4 = accuracy_score(y_pred_train_svm_4, y_train_2)
accuracy_test_svm_4 = accuracy_score(y_pred_test_svm_4, y_test_2)

print("SVM - accuracy_train_schema_2:", accuracy_train_svm_4)
print("SVM - accuracy_test_schema_2:", accuracy_test_svm_4)

SVM - accuracy_train_schema_2: 0.7688434048083171
SVM - accuracy_test_schema_2: 0.7369717642599962

In [38]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_2, y_pred_test_svm_4, target_names=["negative", "neutral", "positive"]
    )
)

              precision    recall  f1-score   support

    negative       0.77      0.89      0.82      3315
     neutral       1.00      0.01      0.02       388
    positive       0.65      0.60      0.63      1574

    accuracy                           0.74      5277
   macro avg       0.81      0.50      0.49      5277
weighted avg       0.75      0.74      0.71      5277

**Random Forest dengan TF-IDF (80/20)**

In [39]:
from sklearn.ensemble import RandomForestClassifier

rf_1 = RandomForestClassifier().fit(X_tfidf_train_1, y_train_1)

y_pred_train_rf_1 = rf_1.predict(X_tfidf_train_1)
y_pred_test_rf_1 = rf_1.predict(X_tfidf_test_1)

accuracy_train_rf_1 = accuracy_score(y_pred_train_rf_1, y_train_1)
accuracy_test_rf_1 = accuracy_score(y_pred_test_rf_1, y_test_1)

print("Random Forest - accuracy_train_schema_1:", accuracy_train_rf_1)
print("Random Forest - accuracy_test_schema_1:", accuracy_test_rf_1)

Random Forest - accuracy_train_schema_1: 1.0
Random Forest - accuracy_test_schema_1: 0.7765776009096077

In [40]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_1, y_pred_test_rf_1, target_names=["negative", "neutral", "positive"]
    )
)

              precision    recall  f1-score   support

    negative       0.77      0.94      0.85      2169
     neutral       0.62      0.12      0.20       249
    positive       0.80      0.59      0.68      1100

    accuracy                           0.78      3518
   macro avg       0.73      0.55      0.58      3518
weighted avg       0.77      0.78      0.75      3518

**Random Forest dengan TF-IDF (70/30)**

In [41]:
from sklearn.ensemble import RandomForestClassifier

rf_2 = RandomForestClassifier().fit(X_tfidf_train_2, y_train_2)

y_pred_train_rf_2 = rf_2.predict(X_tfidf_train_2)
y_pred_test_rf_2 = rf_2.predict(X_tfidf_test_2)

accuracy_train_rf_2 = accuracy_score(y_pred_train_rf_2, y_train_2)
accuracy_test_rf_2 = accuracy_score(y_pred_test_rf_2, y_test_2)

print("Random Forest - accuracy_train_schema_2:", accuracy_train_rf_2)
print("Random Forest - accuracy_test_schema_2:", accuracy_test_rf_2)

Random Forest - accuracy_train_schema_2: 1.0
Random Forest - accuracy_test_schema_2: 0.7714610574189881

In [42]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_2, y_pred_test_rf_2, target_names=["negative", "neutral", "positive"]
    )
)

              precision    recall  f1-score   support

    negative       0.77      0.95      0.85      3315
     neutral       0.56      0.10      0.17       388
    positive       0.80      0.56      0.66      1574

    accuracy                           0.77      5277
   macro avg       0.71      0.54      0.56      5277
weighted avg       0.76      0.77      0.74      5277

**Random Forest dengan Word2Vector (80/20)**

In [43]:
from sklearn.ensemble import RandomForestClassifier

rf_3 = RandomForestClassifier().fit(X_w2v_train_1, y_train_1)

y_pred_train_rf_3 = rf_3.predict(X_w2v_train_1)
y_pred_test_rf_3 = rf_3.predict(X_w2v_test_1)

accuracy_train_rf_3 = accuracy_score(y_pred_train_rf_3, y_train_1)
accuracy_test_rf_3 = accuracy_score(y_pred_test_rf_3, y_test_1)

print("Random Forest - accuracy_train_schema_2:", accuracy_train_rf_3)
print("Random Forest - accuracy_test_schema_2:", accuracy_test_rf_3)

Random Forest - accuracy_train_schema_2: 1.0
Random Forest - accuracy_test_schema_2: 0.7157475838544628

In [44]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_1, y_pred_test_rf_3, target_names=["negative", "neutral", "positive"]
    )
)

              precision    recall  f1-score   support

    negative       0.74      0.89      0.81      2169
     neutral       0.62      0.03      0.06       249
    positive       0.64      0.52      0.57      1100

    accuracy                           0.72      3518
   macro avg       0.67      0.48      0.48      3518
weighted avg       0.70      0.72      0.68      3518

**Random Forest dengan Word2Vector (70/30)**

In [45]:
from sklearn.ensemble import RandomForestClassifier

rf_4 = RandomForestClassifier().fit(X_w2v_train_2, y_train_2)

y_pred_train_rf_4 = rf_4.predict(X_w2v_train_2)
y_pred_test_rf_4 = rf_4.predict(X_w2v_test_2)

accuracy_train_rf_4 = accuracy_score(y_pred_train_rf_4, y_train_2)
accuracy_test_rf_4 = accuracy_score(y_pred_test_rf_4, y_test_2)

print("Random Forest - accuracy_train_schema_2:", accuracy_train_rf_4)
print("Random Forest - accuracy_test_schema_2:", accuracy_test_rf_4)

Random Forest - accuracy_train_schema_2: 1.0
Random Forest - accuracy_test_schema_2: 0.7138525677468258

In [46]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_2, y_pred_test_rf_4, target_names=["negative", "neutral", "positive"]
    )
)

              precision    recall  f1-score   support

    negative       0.74      0.90      0.81      3315
     neutral       0.57      0.02      0.04       388
    positive       0.64      0.49      0.55      1574

    accuracy                           0.71      5277
   macro avg       0.65      0.47      0.47      5277
weighted avg       0.70      0.71      0.68      5277

In [47]:
results = pd.DataFrame(
    [
        {
            "Model": "SVM",
            "Fitur": "TF-IDF",
            "Schema": "80:20",
            "Accuracy Train": accuracy_train_svm_1 * 100,
            "Accuracy Test": accuracy_test_svm_1 * 100,
        },
        {
            "Model": "SVM",
            "Fitur": "TF-IDF",
            "Schema": "70:30",
            "Accuracy Train": accuracy_train_svm_2 * 100,
            "Accuracy Test": accuracy_test_svm_2 * 100,
        },
        {
            "Model": "SVM",
            "Fitur": "Word2Vec",
            "Schema": "80:20",
            "Accuracy Train": accuracy_train_svm_3 * 100,
            "Accuracy Test": accuracy_test_svm_3 * 100,
        },
        {
            "Model": "SVM",
            "Fitur": "Word2Vec",
            "Schema": "70:30",
            "Accuracy Train": accuracy_train_svm_4 * 100,
            "Accuracy Test": accuracy_test_svm_4 * 100,
        },
        {
            "Model": "Random Forest",
            "Fitur": "TF-IDF",
            "Schema": "80:20",
            "Accuracy Train": accuracy_train_rf_1 * 100,
            "Accuracy Test": accuracy_test_rf_1 * 100,
        },
        {
            "Model": "Random Forest",
            "Fitur": "TF-IDF",
            "Schema": "70:30",
            "Accuracy Train": accuracy_train_rf_2 * 100,
            "Accuracy Test": accuracy_test_rf_2 * 100,
        },
        {
            "Model": "Random Forest",
            "Fitur": "Word2Vec",
            "Schema": "80:20",
            "Accuracy Train": accuracy_train_rf_3 * 100,
            "Accuracy Test": accuracy_test_rf_3 * 100,
        },
        {
            "Model": "Random Forest",
            "Fitur": "Word2Vec",
            "Schema": "70:30",
            "Accuracy Train": accuracy_train_rf_4 * 100,
            "Accuracy Test": accuracy_test_rf_4 * 100,
        },
    ]
)

results

           Model     Fitur Schema  Accuracy Train  Accuracy Test
0            SVM    TF-IDF  80:20       93.603866      87.123366
1            SVM    TF-IDF  70:30       94.282001      86.450635
2            SVM  Word2Vec  80:20       76.689645      73.166572
3            SVM  Word2Vec  70:30       76.884340      73.697176
4  Random Forest    TF-IDF  80:20      100.000000      77.657760
5  Random Forest    TF-IDF  70:30      100.000000      77.146106
6  Random Forest  Word2Vec  80:20      100.000000      71.574758
7  Random Forest  Word2Vec  70:30      100.000000      71.385257

# 7.Inference

In [69]:
ulasan = [
    "Mobile Legends ini sekarang semakin bagus dan seru dimainkan",
    "Game ini sangat buruk, sering lag dan disconnect",
    "Update terbaru biasa saja, tidak ada perubahan yang signifikan",
    "Grafiknya bagus tetapi sering sekali lag",
    "Saya suka sekali bermain Mobile Legends",
    "Game sampah, matchmaking sangat buruk",
    "Setelah update hanya login dan bermain seperti biasa",
]

**Preprocessing**

In [70]:
def text_preprocessing(doc):
    doc = [text.lower() for text in doc]
    doc = [re.sub(r"@[A-Za-z0-9]+", "", text) for text in doc]
    doc = [re.sub(r"#[A-Za-z0-9]+", "", text) for text in doc]
    doc = [re.sub(r"RT[\s]", "", text) for text in doc]
    doc = [re.sub(r"http\S+", "", text) for text in doc]
    doc = [re.sub(r"[0-9]+", "", text) for text in doc]
    doc = [re.sub(r"[^\w\s]", "", text) for text in doc]
    doc = [
        " ".join([slangwords.get(word.lower(), word) for word in text.split()])
        for text in doc
    ]
    doc = [
        " ".join([word for word in text.split() if word not in stopwords_id])
        for text in doc
    ]
    doc = [word_tokenize(text) for text in doc]
    doc = [[stemmer.stem(token) for token in tokens] for tokens in doc]

    return doc

In [71]:
def inference_sentiment(text):

    # Preprocessing teks
    tokens = text_preprocessing([text])[0]

    # Mengubah token menjadi satu string
    cleaned_text = " ".join(tokens)

    # Feature extraction menggunakan TF-IDF
    vector = tfidfvec.transform([cleaned_text])

    # Prediksi menggunakan SVM terbaik
    prediction = svm_1.predict(vector)[0]

    return prediction

In [72]:
hasil_inference = []

for ulasan in ulasan:

    hasil = inference_sentiment(ulasan)

    hasil_inference.append({"Ulasan": ulasan, "Prediksi Sentimen": hasil})

hasil_inference_df = pd.DataFrame(hasil_inference)

hasil_inference_df

                                              Ulasan Prediksi Sentimen
0  Mobile Legends ini sekarang semakin bagus dan ...          negative
1   Game ini sangat buruk, sering lag dan disconnect          negative
2  Update terbaru biasa saja, tidak ada perubahan...          negative
3           Grafiknya bagus tetapi sering sekali lag          negative
4            Saya suka sekali bermain Mobile Legends           postive
5              Game sampah, matchmaking sangat buruk          negative
6  Setelah update hanya login dan bermain seperti...          negative

In [73]:
hasil_inference_df.to_csv("hasil_inference_SVM_TF-IDF_80_20.csv")

# 8.Dokumentasi Hasil
**Membuat CSV dari Hasil Preprocessing dan Latih Model**

In [51]:
results.to_csv("Hasil_Perbandingan_Model_Sentiment_Analysis.csv")

In [52]:
df_clean.to_csv("Ulasan_Apk_Mobile_Legends_Processed.csv")

In [74]:
import joblib
import os

# Membuat folder penyimpanan model
os.makedirs("saved_models", exist_ok=True)
joblib.dump(svm_1, "saved_models/svm_tfidf_80_20.pkl")
joblib.dump(svm_2, "saved_models/svm_tfidf_70_30.pkl")
joblib.dump(svm_3, "saved_models/svm_word2vec_80_20.pkl")
joblib.dump(svm_4, "saved_models/svm_word2vec_70_30.pkl")
joblib.dump(rf_1, "saved_models/rf_tfidf_80_20.pkl")
joblib.dump(rf_2, "saved_models/rf_tfidf_70_30.pkl")
joblib.dump(rf_3, "saved_models/rf_word2vec_80_20.pkl")
joblib.dump(rf_4, "saved_models/rf_word2vec_70_30.pkl")
joblib.dump(tfidfvec, "saved_models/tfidf_vectorizer.pkl")
model.save("saved_models/word2vec.model")

print("Word2Vec berhasil disimpan.")


print("Semua model dan TF-IDF berhasil disimpan.")

Word2Vec berhasil disimpan.
Semua model dan TF-IDF berhasil disimpan.